DROP TABLE IF EXISTS review_logs;
DROP TABLE IF EXISTS vocabularies;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(255) UNIQUE NOT NULL, 
    username VARCHAR(50) DEFAULT 'Kang Mus', 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vocabularies (
    id SERIAL PRIMARY KEY,
    kanji VARCHAR(50),
    kana VARCHAR(50) NOT NULL,
    romaji VARCHAR(100) NOT NULL,
    meaning TEXT NOT NULL,
    example_sentence TEXT,
    difficulty_level INTEGER DEFAULT 1 
);

CREATE TABLE review_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
    vocab_id INTEGER REFERENCES vocabularies(id) ON DELETE CASCADE,
    reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result INTEGER CHECK (result IN (0, 1, 2)) 
);


INSERT INTO vocabularies (kanji, kana, romaji, meaning, example_sentence, difficulty_level) VALUES
----- Entry level/N5 Voacabs -----
-- ORANG & KATA GANTI (N5)
('私', 'わたし', 'watashi', 'Saya', '私は学生です (Saya adalah murid)', 1),
('あなた', 'あなた', 'anata', 'Anda/Kamu', 'あなたは誰ですか (Siapa Anda?)', 1),
('彼', 'かれ', 'kare', 'Dia (Laki-laki)', '彼は私の友達です (Dia teman saya)', 1),
('彼女', 'かのじょ', 'kanojo', 'Dia (Perempuan)', '彼女は親切です (Dia ramah)', 1),
('先生', 'せんせい', 'sensei', 'Guru', '先生、質問があります (Guru, saya ada pertanyaan)', 1),
('学生', 'がくせい', 'gakusei', 'Siswa', '彼は大学の学生です (Dia mahasiswa)', 1),
('留学生', 'りゅうがくせい', 'ryuugakusei', 'Pelajar Asing', '私は留学生です (Saya pelajar asing)', 1),
('友達', 'ともだち', 'tomodachi', 'Teman', '友達と遊びます (Bermain dengan teman)', 1),
('家族', 'かぞく', 'kazoku', 'Keluarga', '家族は4人です (Keluarga saya 4 orang)', 1),
('父', 'ちち', 'chichi', 'Ayah (Sendiri)', '父は会社員です (Ayah saya karyawan)', 1),
('母', 'はは', 'haha', 'Ibu (Sendiri)', '母は料理が好きです (Ibu suka memasak)', 1),
('お父さん', 'おとうさん', 'otousan', 'Ayah (Orang)', 'お父さんは元気？ (Ayahmu sehat?)', 1),
('お母さん', 'おかあさん', 'okaasan', 'Ibu (Orang)', 'お母さんに会いたい (Ingin bertemu ibu)', 1),
('人', 'ひと', 'hito', 'Orang', 'あの人は誰ですか (Orang itu siapa?)', 1),
('大人', 'おとな', 'otona', 'Dewasa', '大人の切符 (Tiket dewasa)', 1),
('子供', 'こども', 'kodomo', 'Anak-anak', '子供が遊んでいる (Anak-anak sedang bermain)', 1),
('男', 'おとこ', 'otoko', 'Laki-laki', '男の子 (Anak laki-laki)', 1),
('女', 'おんな', 'onna', 'Perempuan', '女の子 (Anak perempuan)', 1),

-- WAKTU (N5)
('時間', 'じかん', 'jikan', 'Waktu', '時間がありません (Tidak ada waktu)', 1),
('今', 'いま', 'ima', 'Sekarang', '今は3時です (Sekarang jam 3)', 1),
('今日', 'きょう', 'kyou', 'Hari ini', '今日は暑いです (Hari ini panas)', 1),
('昨日', 'きのう', 'kinou', 'Kemarin', '昨日は雨でした (Kemarin hujan)', 1),
('明日', 'あした', 'ashita', 'Besok', '明日会いましょう (Ayo bertemu besok)', 1),
('毎日', 'まいにち', 'mainichi', 'Setiap hari', '毎日勉強します (Setiap hari belajar)', 1),
('朝', 'あさ', 'asa', 'Pagi', '朝ごはんを食べます (Makan pagi)', 1),
('昼', 'ひる', 'hiru', 'Siang', '昼ごはんを食べましたか (Sudah makan siang?)', 1),
('晩', 'ばん', 'ban', 'Malam', '晩ごはんはカレーです (Makan malam kari)', 1),
('夜', 'よる', 'yoru', 'Malam (Larut)', '夜に寝ます (Tidur di malam hari)', 1),
('週', 'しゅう', 'shuu', 'Minggu', '来週、旅行に行きます (Minggu depan liburan)', 1),
('月', 'つき', 'tsuki', 'Bulan', '月が出ている (Bulan muncul)', 1),
('年', 'とし', 'toshi', 'Tahun', '今年は2025年です (Tahun ini 2025)', 1),
('来年', 'らいねん', 'rainen', 'Tahun Depan', '来年日本へ行きます (Tahun depan ke Jepang)', 1),
('去年', 'きょねん', 'kyonen', 'Tahun Lalu', '去年の冬 (Musim dingin lalu)', 1),

-- BENDA & MAKANAN (N5)
('水', 'みず', 'mizu', 'Air', '水をください (Minta air)', 1),
('ご飯', 'ごはん', 'gohan', 'Nasi', '朝ご飯 (Sarapan)', 1),
('パン', 'ぱん', 'pan', 'Roti', 'パンを食べる (Makan roti)', 1),
('魚', 'さかな', 'sakana', 'Ikan', '魚が好きです (Suka ikan)', 1),
('肉', 'にく', 'niku', 'Daging', '肉を食べません (Tidak makan daging)', 1),
('卵', 'たまご', 'tamago', 'Telur', '卵を買う (Beli telur)', 1),
('野菜', 'やさい', 'yasai', 'Sayuran', '野菜は体にいい (Sayur bagus untuk tubuh)', 1),
('果物', 'くだもの', 'kudamono', 'Buah', '果物が好き (Suka buah)', 1),
('本', 'ほん', 'hon', 'Buku', '本を読む (Baca buku)', 1),
('辞書', 'じしょ', 'jisho', 'Kamus', '辞書を使う (Pakai kamus)', 1),
('鉛筆', 'えんぴつ', 'enpitsu', 'Pensil', '鉛筆で書く (Menulis pakai pensil)', 1),
('鞄', 'かばん', 'kaban', 'Tas', '鞄の中に (Di dalam tas)', 1),
('傘', 'かさ', 'kasa', 'Payung', '傘を忘れた (Lupa payung)', 1),
('お金', 'おかね', 'okane', 'Uang', 'お金がない (Tidak ada uang)', 1),
('時計', 'とけい', 'tokei', 'Jam', '時計を見る (Lihat jam)', 1),
('電話', 'でんわ', 'denwa', 'Telepon', '電話をかける (Menelepon)', 1),
('車', 'くるま', 'kuruma', 'Mobil', '車に乗る (Naik mobil)', 1),
('自転車', 'じてんしゃ', 'jitensha', 'Sepeda', '自転車で行く (Pergi naik sepeda)', 1),
('電車', 'でんしゃ', 'densha', 'Kereta', '電車が来ました (Kereta datang)', 1),
('飛行機', 'ひこうき', 'hikouki', 'Pesawat', '飛行機で飛ぶ (Terbang dengan pesawat)', 1),

-- TEMPAT (N5)
('学校', 'がっこう', 'gakkou', 'Sekolah', '学校へ行く (Ke sekolah)', 1),
('家', 'いえ', 'ie', 'Rumah', '家に帰る (Pulang ke rumah)', 1),
('店', 'みせ', 'mise', 'Toko', '店が開く (Toko buka)', 1),
('駅', 'えき', 'eki', 'Stasiun', '駅で待つ (Tunggu di stasiun)', 1),
('会社', 'かいしゃ', 'kaisha', 'Kantor', '会社で働く (Kerja di kantor)', 1),
('病院', 'びょういん', 'byouin', 'Rumah Sakit', '病院へ行く (Ke RS)', 1),
('部屋', 'へや', 'heya', 'Kamar', '私の部屋 (Kamar saya)', 1),
('トイレ', 'といれ', 'toire', 'Toilet', 'トイレはどこ？ (Toilet dimana?)', 1),
('銀行', 'ぎんこう', 'ginkou', 'Bank', '銀行でおろす (Ambil uang di bank)', 1),
('図書館', 'としょかん', 'toshokan', 'Perpustakaan', '図書館で勉強 (Belajar di perpus)', 1),
('交番', 'こうばん', 'kouban', 'Pos Polisi', '交番で聞く (Tanya di pos polisi)', 1),
('公園', 'こうえん', 'kouen', 'Taman', '公園を散歩 (Jalan di taman)', 1),

-- KATA SIFAT DASAR (N5)
('大きい', 'おおきい', 'ookii', 'Besar', '大きい家 (Rumah besar)', 1),
('小さい', 'ちいさい', 'chiisai', 'Kecil', '小さい猫 (Kucing kecil)', 1),
('高い', 'たかい', 'takai', 'Mahal/Tinggi', '高い山 (Gunung tinggi)', 1),
('安い', 'やすい', 'yasui', 'Murah', '安い店 (Toko murah)', 1),
('新しい', 'あたらしい', 'atarashii', 'Baru', '新しい本 (Buku baru)', 1),
('古い', 'ふるい', 'furui', 'Lama', '古い時計 (Jam lama)', 1),
('良い', 'よい', 'yoi', 'Bagus', '良い天気 (Cuaca bagus)', 1),
('悪い', 'わるい', 'warui', 'Buruk', '気分が悪い (Perasaan buruk)', 1),
('暑い', 'あつい', 'atsui', 'Panas', '今日は暑い (Hari ini panas)', 1),
('寒い', 'さむい', 'samui', 'Dingin', '外は寒い (Di luar dingin)', 1),
('美味しい', 'おいしい', 'oishii', 'Enak', '美味しい寿司 (Sushi enak)', 1),
('面白い', 'おもしろい', 'omoshiroi', 'Menarik', '面白い映画 (Film menarik)', 1),
('忙しい', 'いそがしい', 'isogashii', 'Sibuk', '仕事が忙しい (Kerja sibuk)', 1),
('楽しい', 'たのしい', 'tanoshii', 'Menyenangkan', '楽しい旅行 (Liburan menyenangkan)', 1),
('難しい', 'むずかしい', 'muzukashii', 'Sulit', '日本語は難しい (Jepang itu sulit)', 1),
('易しい', 'やさしい', 'yasashii', 'Mudah', '易しい問題 (Soal mudah)', 1),
('好き', 'すき', 'suki', 'Suka', '猫が好き (Suka kucing)', 1),
('嫌い', 'きらい', 'kirai', 'Benci', '虫が嫌い (Benci serangga)', 1),
('上手', 'じょうず', 'jouzu', 'Pintar/Jago', '歌が上手 (Jago nyanyi)', 1),
('下手', 'へた', 'heta', 'Bodoh/Tidak bisa', '絵が下手 (Gak bisa gambar)', 1),
('きれい', 'きれい', 'kirei', 'Cantik/Bersih', 'きれいな花 (Bunga cantik)', 1),
('静か', 'しずか', 'shizuka', 'Tenang', '静かな部屋 (Kamar tenang)', 1),
('元気', 'げんき', 'genki', 'Sehat', '元気ですか (Apa kabar?)', 1),
('有名', 'ゆうめい', 'yuumei', 'Terkenal', '有名な人 (Orang terkenal)', 1),

-- KATA KERJA DASAR (N5)
('食べる', 'たべる', 'taberu', 'Makan', 'ご飯を食べる (Makan nasi)', 1),
('飲む', 'のむ', 'nomu', 'Minum', '水を飲む (Minum air)', 1),
('見る', 'みる', 'miru', 'Melihat', 'テレビを見る (Nonton TV)', 1),
('聞く', 'きく', 'kiku', 'Mendengar', '音楽を聞く (Dengar musik)', 1),
('行く', 'いく', 'iku', 'Pergi', '学校へ行く (Pergi ke sekolah)', 1),
('来る', 'くる', 'kuru', 'Datang', '友達が来る (Teman datang)', 1),
('帰る', 'かえる', 'kaeru', 'Pulang', '家へ帰る (Pulang ke rumah)', 1),
('寝る', 'ねる', 'neru', 'Tidur', '早く寝る (Tidur cepat)', 1),
('起きる', 'おきる', 'okiru', 'Bangun', '6時に起きる (Bangun jam 6)', 1),
('話す', 'はなす', 'hanasu', 'Berbicara', '日本語を話す (Bicara Jepang)', 1),
('書く', 'かく', 'kaku', 'Menulis', '手紙を書く (Nulis surat)', 1),
('読む', 'よむ', 'yomu', 'Membaca', '本を読む (Baca buku)', 1),
('買う', 'かう', 'kau', 'Membeli', '服を買う (Beli baju)', 1),
('する', 'する', 'suru', 'Melakukan', 'スポーツをする (Olahraga)', 1),
('勉強する', 'べんきょうする', 'benkyou suru', 'Belajar', '英語を勉強する (Belajar Inggris)', 1),
('会う', 'あう', 'au', 'Bertemu', '友達に会う (Ketemu teman)', 1),
('洗う', 'あらう', 'arau', 'Mencuci', '手を洗う (Cuci tangan)', 1),
('歩く', 'あるく', 'aruku', 'Berjalan', '駅まで歩く (Jalan ke stasiun)', 1),
('言う', 'いう', 'iu', 'Berkata', '好きだと言う (Bilang suka)', 1),
('泳ぐ', 'およぐ', 'oyogu', 'Berenang', '海で泳ぐ (Renang di laut)', 1),
('売る', 'うる', 'uru', 'Menjual', '家を売る (Jual rumah)', 1),
('置く', 'おく', 'oku', 'Meletakkan', '机に置く (Taruh di meja)', 1),
('押す', 'おす', 'osu', 'Menekan', 'ボタンを押す (Tekan tombol)', 1),
('終わる', 'おわる', 'owaru', 'Selesai', '仕事が終わる (Kerja selesai)', 1),
('貸す', 'かす', 'kasu', 'Meminjamkan', 'ペンを貸す (Pinjamkan pena)', 1),
('借りる', 'かりる', 'kariru', 'Meminjam', '本を借りる (Pinjam buku)', 1),
('消える', 'きえる', 'kieru', 'Padam', '電気が消える (Listrik padam)', 1),
('切る', 'きる', 'kiru', 'Memotong', '紙を切る (Potong kertas)', 1),
('着る', 'きる', 'kiru', 'Memakai (Baju)', 'シャツを着る (Pakai kemeja)', 1),
('困る', 'こまる', 'komaru', 'Susah', 'お金に困る (Susah uang)', 1),
('咲く', 'さく', 'saku', 'Mekar', '花が咲く (Bunga mekar)', 1),
('閉める', 'しめる', 'shimeru', 'Menutup', 'ドアを閉める (Tutup pintu)', 1),
('知る', 'しる', 'shiru', 'Tahu', 'ニュースを知る (Tahu berita)', 1),
('住む', 'すむ', 'sumu', 'Tinggal', '東京に住む (Tinggal di Tokyo)', 1),
('座る', 'すわる', 'suwaru', 'Duduk', '椅子に座る (Duduk di kursi)', 1),
('立つ', 'たつ', 'tatsu', 'Berdiri', 'ここに立つ (Berdiri disini)', 1),
('使う', 'つかう', 'tsukau', 'Menggunakan', 'パソコンを使う (Pakai PC)', 1),
('着く', 'つく', 'tsuku', 'Tiba', '駅に着く (Tiba di stasiun)', 1),
('作る', 'つくる', 'tsukuru', 'Membuat', '料理を作る (Masak)', 1),
('飛ぶ', 'とぶ', 'tobu', 'Terbang', '鳥が飛ぶ (Burung terbang)', 1),
('止まる', 'とまる', 'tomaru', 'Berhenti', '車が止まる (Mobil berhenti)', 1),
('撮る', 'とる', 'toru', 'Memotret', '写真を撮る (Ambil foto)', 1),
('鳴く', 'なく', 'naku', 'Berkicau', '鳥が鳴く (Burung berkicau)', 1),
('並ぶ', 'ならぶ', 'narabu', 'Berbaris', '列に並ぶ (Antre)', 1),
('なる', 'なる', 'naru', 'Menjadi', '医者になる (Jadi dokter)', 1),
('脱ぐ', 'ぬぐ', 'nugu', 'Melepas', '靴を脱ぐ (Lepas sepatu)', 1),
('乗る', 'のる', 'noru', 'Naik', 'バスに乗る (Naik bus)', 1),
('入る', 'はいる', 'hairu', 'Masuk', '部屋に入る (Masuk kamar)', 1),
('走る', 'はしる', 'hashiru', 'Berlari', '速く走る (Lari cepat)', 1),
('待つ', 'まつ', 'matsu', 'Menunggu', 'バスを待つ (Tunggu bus)', 1),
('持つ', 'もつ', 'motsu', 'Memegang', '荷物を持つ (Bawa barang)', 1),
('呼ぶ', 'よぶ', 'yobu', 'Memanggil', 'タクシーを呼ぶ (Panggil taksi)', 1),
('分かる', 'わかる', 'wakaru', 'Mengerti', '意味が分かる (Mengerti arti)', 1),
('忘れる', 'わすれる', 'wasureru', 'Lupa', '宿題を忘れる (Lupa PR)', 1),
('渡す', 'わたす', 'watasu', 'Menyerahkan', '手紙を渡す (Serahkan surat)', 1),
('渡る', 'わたる', 'wataru', 'Menyeberang', '橋を渡る (Seberangi jembatan)', 1),


-- --- WARNA (N5) ---
('色', 'いろ', 'iro', 'Warna', '何色が好き？ (Suka warna apa?)', 1),
('赤', 'あか', 'aka', 'Merah', '赤いリンゴ (Apel merah)', 1),
('青', 'あお', 'ao', 'Biru', '青い海 (Laut biru)', 1),
('白', 'しろ', 'shiro', 'Putih', '白い雪 (Salju putih)', 1),
('黒', 'くろ', 'kuro', 'Hitam', '黒い猫 (Kucing hitam)', 1),
('黄色', 'きいろ', 'kiiro', 'Kuning', '黄色い花 (Bunga kuning)', 1),
('茶色', 'ちゃいろ', 'chairo', 'Cokelat', '茶色の靴 (Sepatu cokelat)', 1),
('緑', 'みどり', 'midori', 'Hijau', '緑の木 (Pohon hijau)', 1),

-- --- ANGGOTA TUBUH (N5) ---
('体', 'からだ', 'karada', 'Tubuh/Badan', '体が丈夫 (Badan kuat)', 1),
('頭', 'あたま', 'atama', 'Kepala', '頭がいい (Pintar)', 1),
('顔', 'かお', 'kao', 'Wajah', '顔を洗う (Cuci muka)', 1),
('目', 'め', 'me', 'Mata', '目が悪い (Mata buruk/rabun)', 1),
('耳', 'みみ', 'mimi', 'Telinga', '耳が痛い (Sakit telinga)', 1),
('鼻', 'はな', 'hana', 'Hidung', '鼻が高い (Hidung mancung/Sombong)', 1),
('口', 'くち', 'kuchi', 'Mulut', '口を開ける (Buka mulut)', 1),
('歯', 'は', 'ha', 'Gigi', '歯を磨く (Sikat gigi)', 1),
('手', 'て', 'te', 'Tangan', '手を繋ぐ (Gandengan tangan)', 1),
('足', 'あし', 'ashi', 'Kaki', '足が速い (Lari cepat)', 1),
('背', 'せ', 'se', 'Punggung/Tinggi badan', '背が高い (Badan tinggi)', 1),
('髪', 'かみ', 'kami', 'Rambut', '髪を切る (Potong rambut)', 1),
('指', 'ゆび', 'yubi', 'Jari', '指輪 (Cincin)', 1),


----- Immediate/N4 Voacabs -----
-- KATA KERJA N4
('謝る', 'あやまる', 'ayamaru', 'Meminta maaf', '素直に謝る (Minta maaf tulus)', 2),
('急ぐ', 'いそぐ', 'isogu', 'Buru-buru', '急いでください (Tolong buru-buru)', 2),
('祈る', 'いのる', 'inoru', 'Berdoa', '平和を祈る (Berdoa perdamaian)', 2),
('植える', 'うえる', 'ueru', 'Menanam', '木を植える (Tanam pohon)', 2),
('選ぶ', 'えらぶ', 'erabu', 'Memilih', 'これを選ぶ (Pilih ini)', 2),
('遅れる', 'おくれる', 'okureru', 'Terlambat', '電車に遅れる (Telat kereta)', 2),
('怒る', 'おこる', 'okoru', 'Marah', '父が怒る (Ayah marah)', 2),
('落ちる', 'おちる', 'ochiru', 'Jatuh', '葉が落ちる (Daun jatuh)', 2),
('落とす', 'おとす', 'otosu', 'Menjatuhkan', 'ペンを落とす (Jatuhkan pena)', 2),
('踊る', 'おどる', 'odoru', 'Menari', 'ダンスを踊る (Menari)', 2),
('驚く', 'おどろく', 'odoroku', 'Terkejut', '音に驚く (Kaget suara)', 2),
('飾る', 'かざる', 'kazaru', 'Menghias', '部屋を飾る (Hias kamar)', 2),
('片付ける', 'かたづける', 'katazukeru', 'Membereskan', '部屋を片付ける (Bereskan kamar)', 2),
('乾く', 'かわく', 'kawaku', 'Kering', '服が乾く (Baju kering)', 2),
('変わる', 'かわる', 'kawaru', 'Berubah', '色が変わる (Warna berubah)', 2),
('決める', 'きめる', 'kimeru', 'Memutuskan', '進路を決める (Putuskan masa depan)', 2),
('比べる', 'くらべる', 'kuraberu', 'Membandingkan', '背を比べる (Bandingkan tinggi)', 2),
('暮らす', 'くらす', 'kurasu', 'Hidup', '一人で暮らす (Hidup sendiri)', 2),
('混む', 'こむ', 'komu', 'Macet', '道が混む (Jalan macet)', 2),
('壊す', 'こわす', 'kowasu', 'Merusak', '物を壊す (Rusak barang)', 2),
('壊れる', 'こわれる', 'kowareru', 'Rusak', '椅子が壊れる (Kursi rusak)', 2),
('探す', 'さがす', 'sagasu', 'Mencari', '鍵を探す (Cari kunci)', 2),
('下がる', 'さがる', 'sagaru', 'Turun', '熱が下がる (Demam turun)', 2),
('下げる', 'さげる', 'sageru', 'Menurunkan', '頭を下げる (Tunduk kepala)', 2),
('騒ぐ', 'さわぐ', 'sawagu', 'Berisik', '教室で騒ぐ (Berisik di kelas)', 2),
('触る', 'さわる', 'sawaru', 'Menyentuh', '犬に触る (Sentuh anjing)', 2),
('叱る', 'しかる', 'shikaru', 'Memarahi', '子供を叱る (Marahi anak)', 2),
('調べる', 'しらべる', 'shiraberu', 'Memeriksa', '辞書で調べる (Cek kamus)', 2),
('知らせる', 'しらせる', 'shiraseru', 'Memberitahu', 'ニュースを知らせる (Beri kabar)', 2),
('過ぎる', 'すぎる', 'sugiru', 'Melewati', '時間が過ぎる (Waktu lewat)', 2),
('進む', 'すすむ', 'susumu', 'Maju', '前へ進む (Maju depan)', 2),
('捨てる', 'すてる', 'suteru', 'Membuang', 'ゴミを捨てる (Buang sampah)', 2),
('滑る', 'すべる', 'suberu', 'Terpeleset', '氷で滑る (Peleset di es)', 2),
('育てる', 'そだてる', 'sodateru', 'Membesarkan', '花を育てる (Rawat bunga)', 2),
('倒れる', 'たおれる', 'taoreru', 'Roboh', '木が倒れる (Pohon roboh)', 2),
('足す', 'たす', 'tasu', 'Menambah', '水を足す (Tambah air)', 2),
('訪ねる', 'たずねる', 'tazuneru', 'Berkunjung', '家を訪ねる (Berkunjung ke rumah)', 2),
('建てる', 'たてる', 'tateru', 'Membangun', '家を建てる (Bangun rumah)', 2),
('楽しむ', 'たのしむ', 'tanoshimu', 'Menikmati', '生活を楽しむ (Nikmati hidup)', 2),
('足りる', 'たりる', 'tariru', 'Cukup', 'お金が足りる (Uang cukup)', 2),
('捕まえる', 'つかまえる', 'tsukamaeru', 'Menangkap', '泥棒を捕まえる (Tangkap maling)', 2),
('疲れる', 'つかれる', 'tsukareru', 'Lelah', '仕事で疲れる (Lelah kerja)', 2),
('付く', 'つく', 'tsuku', 'Menempel', '埃が付く (Debu nempel)', 2),
('伝える', 'つたえる', 'tsutaeru', 'Menyampaikan', '気持ちを伝える (Sampaikan rasa)', 2),
('続く', 'つづく', 'tsuzuku', 'Berlanjut', '雨が続く (Hujan lanjut)', 2),
('続ける', 'つづける', 'tsuzukeru', 'Melanjutkan', '勉強を続ける (Lanjut belajar)', 2),
('包む', 'つつむ', 'tsutsumu', 'Membungkus', '紙で包む (Bungkus kertas)', 2),
('釣る', 'つる', 'tsuru', 'Memancing', '魚を釣る (Mancing ikan)', 2),
('手伝う', 'てつだう', 'tetsudau', 'Membantu', '母を手伝う (Bantu ibu)', 2),
('直す', 'なおす', 'naosu', 'Memperbaiki', '時計を直す (Perbaiki jam)', 2),
('治る', 'なおる', 'naoru', 'Sembuh', '病気が治る (Sembuh sakit)', 2),
('亡くなる', 'なくなる', 'nakunaru', 'Meninggal', '祖父が亡くなる (Kakek meninggal)', 2),
('投げる', 'なげる', 'nageru', 'Melempar', 'ボールを投げる (Lempar bola)', 2),
('慣れる', 'なれる', 'nareru', 'Terbiasa', '仕事に慣れる (Biasa kerja)', 2),
('逃げる', 'にげる', 'nigeru', 'Kabur', '速く逃げる (Kabur cepat)', 2),
('似る', 'にる', 'niru', 'Mirip', '母に似る (Mirip ibu)', 2),
('盗む', 'ぬすむ', 'nusumu', 'Mencuri', '金を盗む (Curi uang)', 2),
('塗る', 'ぬる', 'nuru', 'Mengecat', 'ペンキを塗る (Cat tembok)', 2),
('濡れる', 'ぬれる', 'nureru', 'Basah', '雨で濡れる (Basah hujan)', 2),
('残る', 'のこる', 'nokoru', 'Tersisa', '食事が残る (Makanan sisa)', 2),
('運ぶ', 'はこぶ', 'hakobu', 'Mengangkut', '荷物を運ぶ (Angkut barang)', 2),
('始める', 'はじめる', 'hajimeru', 'Memulai', '勉強を始める (Mulai belajar)', 2),
('払う', 'はらう', 'harau', 'Membayar', '代金を払う (Bayar tagihan)', 2),
('冷える', 'ひえる', 'hieru', 'Dingin', '体が冷える (Badan dingin)', 2),
('光る', 'ひかる', 'hikaru', 'Bersinar', '星が光る (Bintang bersinar)', 2),
('増える', 'ふえる', 'fueru', 'Bertambah', '貯金が増える (Tabungan nambah)', 2),
('太る', 'ふとる', 'futoru', 'Gemuk', '最近太る (Baru ini gemuk)', 2),
('踏む', 'ふむ', 'fumu', 'Menginjak', '足を踏む (Injak kaki)', 2),
('褒める', 'ほめる', 'homeru', 'Memuji', '人を褒める (Puji orang)', 2),
('負ける', 'まける', 'makeru', 'Kalah', '試合に負ける (Kalah tanding)', 2),
('間違える', 'まちがえる', 'machigaeru', 'Salah', '道を間違える (Salah jalan)', 2),
('間に合う', 'まにあう', 'maniau', 'Keburu', 'バスに間に合う (Keburu bus)', 2),
('見つかる', 'みつかる', 'mitsukaru', 'Ketemu', '鍵が見つかる (Kunci ketemu)', 2),
('見つける', 'みつける', 'mitsukeru', 'Menemukan', '良い本を見つける (Temukan buku)', 2),
('向かう', 'むかう', 'mukau', 'Menuju', '家へ向かう (Menuju rumah)', 2),
('迎える', 'むかえる', 'mukaeru', 'Menjemput', '客を迎える (Jemput tamu)', 2),
('戻る', 'もどる', 'modoru', 'Kembali', '席に戻る (Kembali duduk)', 2),
('焼く', 'やく', 'yaku', 'Membakar', '肉を焼く (Bakar daging)', 2),
('役に立つ', 'やくにたつ', 'yakunitatsu', 'Berguna', 'この本は役に立つ (Buku ini guna)', 2),
('痩せる', 'やせる', 'yaseru', 'Kurus', '運動して痩せる (Kurus olahraga)', 2),
('止む', 'やむ', 'yamu', 'Berhenti (Hujan)', '雨が止む (Hujan stop)', 2),
('汚れる', 'よごれる', 'yogoreru', 'Kotor', '服が汚れる (Baju kotor)', 2),
('沸かす', 'わかす', 'wakasu', 'Merebus', '湯を沸かす (Rebus air)', 2),
('沸く', 'わく', 'waku', 'Mendidih', '湯が沸く (Air mendidih)', 2),
('割れる', 'われる', 'wareru', 'Pecah', '窓が割れる (Jendela pecah)', 2),

