DROP TABLE IF EXISTS review_logs;
DROP TABLE IF EXISTS vocabularies;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(255) UNIQUE NOT NULL, 
    username VARCHAR(50) DEFAULT 'Kang Mus', 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vocabularies (
    id SERIAL PRIMARY KEY,
    kanji VARCHAR(50),
    kana VARCHAR(50) NOT NULL,
    romaji VARCHAR(100) NOT NULL,
    meaning TEXT NOT NULL,
    example_sentence TEXT,
    difficulty_level INTEGER DEFAULT 1 
);

CREATE TABLE review_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
    vocab_id INTEGER REFERENCES vocabularies(id) ON DELETE CASCADE,
    reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result INTEGER CHECK (result IN (0, 1, 2)) 
);


INSERT INTO vocabularies (kanji, kana, romaji, meaning, example_sentence, difficulty_level) VALUES
----- Entry level/N5 Voacabs -----
-- ORANG & KATA GANTI (N5)
('私', 'わたし', 'watashi', 'Saya', '私は学生です (Saya adalah murid)', 1),
('あなた', 'あなた', 'anata', 'Anda/Kamu', 'あなたは誰ですか (Siapa Anda?)', 1),
('彼', 'かれ', 'kare', 'Dia (Laki-laki)', '彼は私の友達です (Dia teman saya)', 1),
('彼女', 'かのじょ', 'kanojo', 'Dia (Perempuan)', '彼女は親切です (Dia ramah)', 1),
('先生', 'せんせい', 'sensei', 'Guru', '先生、質問があります (Guru, saya ada pertanyaan)', 1),
('学生', 'がくせい', 'gakusei', 'Siswa', '彼は大学の学生です (Dia mahasiswa)', 1),
('留学生', 'りゅうがくせい', 'ryuugakusei', 'Pelajar Asing', '私は留学生です (Saya pelajar asing)', 1),
('友達', 'ともだち', 'tomodachi', 'Teman', '友達と遊びます (Bermain dengan teman)', 1),
('家族', 'かぞく', 'kazoku', 'Keluarga', '家族は4人です (Keluarga saya 4 orang)', 1),
('父', 'ちち', 'chichi', 'Ayah (Sendiri)', '父は会社員です (Ayah saya karyawan)', 1),
('母', 'はは', 'haha', 'Ibu (Sendiri)', '母は料理が好きです (Ibu suka memasak)', 1),
('お父さん', 'おとうさん', 'otousan', 'Ayah (Orang)', 'お父さんは元気？ (Ayahmu sehat?)', 1),
('お母さん', 'おかあさん', 'okaasan', 'Ibu (Orang)', 'お母さんに会いたい (Ingin bertemu ibu)', 1),
('人', 'ひと', 'hito', 'Orang', 'あの人は誰ですか (Orang itu siapa?)', 1),
('大人', 'おとな', 'otona', 'Dewasa', '大人の切符 (Tiket dewasa)', 1),
('子供', 'こども', 'kodomo', 'Anak-anak', '子供が遊んでいる (Anak-anak sedang bermain)', 1),
('男', 'おとこ', 'otoko', 'Laki-laki', '男の子 (Anak laki-laki)', 1),
('女', 'おんな', 'onna', 'Perempuan', '女の子 (Anak perempuan)', 1),

-- WAKTU (N5)
('時間', 'じかん', 'jikan', 'Waktu', '時間がありません (Tidak ada waktu)', 1),
('今', 'いま', 'ima', 'Sekarang', '今は3時です (Sekarang jam 3)', 1),
('今日', 'きょう', 'kyou', 'Hari ini', '今日は暑いです (Hari ini panas)', 1),
('昨日', 'きのう', 'kinou', 'Kemarin', '昨日は雨でした (Kemarin hujan)', 1),
('明日', 'あした', 'ashita', 'Besok', '明日会いましょう (Ayo bertemu besok)', 1),
('毎日', 'まいにち', 'mainichi', 'Setiap hari', '毎日勉強します (Setiap hari belajar)', 1),
('朝', 'あさ', 'asa', 'Pagi', '朝ごはんを食べます (Makan pagi)', 1),
('昼', 'ひる', 'hiru', 'Siang', '昼ごはんを食べましたか (Sudah makan siang?)', 1),
('晩', 'ばん', 'ban', 'Malam', '晩ごはんはカレーです (Makan malam kari)', 1),
('夜', 'よる', 'yoru', 'Malam (Larut)', '夜に寝ます (Tidur di malam hari)', 1),
('週', 'しゅう', 'shuu', 'Minggu', '来週、旅行に行きます (Minggu depan liburan)', 1),
('月', 'つき', 'tsuki', 'Bulan', '月が出ている (Bulan muncul)', 1),
('年', 'とし', 'toshi', 'Tahun', '今年は2025年です (Tahun ini 2025)', 1),
('来年', 'らいねん', 'rainen', 'Tahun Depan', '来年日本へ行きます (Tahun depan ke Jepang)', 1),
('去年', 'きょねん', 'kyonen', 'Tahun Lalu', '去年の冬 (Musim dingin lalu)', 1),

-- BENDA & MAKANAN (N5)
('水', 'みず', 'mizu', 'Air', '水をください (Minta air)', 1),
('ご飯', 'ごはん', 'gohan', 'Nasi', '朝ご飯 (Sarapan)', 1),
('パン', 'ぱん', 'pan', 'Roti', 'パンを食べる (Makan roti)', 1),
('魚', 'さかな', 'sakana', 'Ikan', '魚が好きです (Suka ikan)', 1),
('肉', 'にく', 'niku', 'Daging', '肉を食べません (Tidak makan daging)', 1),
('卵', 'たまご', 'tamago', 'Telur', '卵を買う (Beli telur)', 1),
('野菜', 'やさい', 'yasai', 'Sayuran', '野菜は体にいい (Sayur bagus untuk tubuh)', 1),
('果物', 'くだもの', 'kudamono', 'Buah', '果物が好き (Suka buah)', 1),
('本', 'ほん', 'hon', 'Buku', '本を読む (Baca buku)', 1),
('辞書', 'じしょ', 'jisho', 'Kamus', '辞書を使う (Pakai kamus)', 1),
('鉛筆', 'えんぴつ', 'enpitsu', 'Pensil', '鉛筆で書く (Menulis pakai pensil)', 1),
('鞄', 'かばん', 'kaban', 'Tas', '鞄の中に (Di dalam tas)', 1),
('傘', 'かさ', 'kasa', 'Payung', '傘を忘れた (Lupa payung)', 1),
('お金', 'おかね', 'okane', 'Uang', 'お金がない (Tidak ada uang)', 1),
('時計', 'とけい', 'tokei', 'Jam', '時計を見る (Lihat jam)', 1),
('電話', 'でんわ', 'denwa', 'Telepon', '電話をかける (Menelepon)', 1),
('車', 'くるま', 'kuruma', 'Mobil', '車に乗る (Naik mobil)', 1),
('自転車', 'じてんしゃ', 'jitensha', 'Sepeda', '自転車で行く (Pergi naik sepeda)', 1),
('電車', 'でんしゃ', 'densha', 'Kereta', '電車が来ました (Kereta datang)', 1),
('飛行機', 'ひこうき', 'hikouki', 'Pesawat', '飛行機で飛ぶ (Terbang dengan pesawat)', 1),

-- TEMPAT (N5)
('学校', 'がっこう', 'gakkou', 'Sekolah', '学校へ行く (Ke sekolah)', 1),
('家', 'いえ', 'ie', 'Rumah', '家に帰る (Pulang ke rumah)', 1),
('店', 'みせ', 'mise', 'Toko', '店が開く (Toko buka)', 1),
('駅', 'えき', 'eki', 'Stasiun', '駅で待つ (Tunggu di stasiun)', 1),
('会社', 'かいしゃ', 'kaisha', 'Kantor', '会社で働く (Kerja di kantor)', 1),
('病院', 'びょういん', 'byouin', 'Rumah Sakit', '病院へ行く (Ke RS)', 1),
('部屋', 'へや', 'heya', 'Kamar', '私の部屋 (Kamar saya)', 1),
('トイレ', 'といれ', 'toire', 'Toilet', 'トイレはどこ？ (Toilet dimana?)', 1),
('銀行', 'ぎんこう', 'ginkou', 'Bank', '銀行でおろす (Ambil uang di bank)', 1),
('図書館', 'としょかん', 'toshokan', 'Perpustakaan', '図書館で勉強 (Belajar di perpus)', 1),
('交番', 'こうばん', 'kouban', 'Pos Polisi', '交番で聞く (Tanya di pos polisi)', 1),
('公園', 'こうえん', 'kouen', 'Taman', '公園を散歩 (Jalan di taman)', 1),

-- KATA SIFAT DASAR (N5)
('大きい', 'おおきい', 'ookii', 'Besar', '大きい家 (Rumah besar)', 1),
('小さい', 'ちいさい', 'chiisai', 'Kecil', '小さい猫 (Kucing kecil)', 1),
('高い', 'たかい', 'takai', 'Mahal/Tinggi', '高い山 (Gunung tinggi)', 1),
('安い', 'やすい', 'yasui', 'Murah', '安い店 (Toko murah)', 1),
('新しい', 'あたらしい', 'atarashii', 'Baru', '新しい本 (Buku baru)', 1),
('古い', 'ふるい', 'furui', 'Lama', '古い時計 (Jam lama)', 1),
('良い', 'よい', 'yoi', 'Bagus', '良い天気 (Cuaca bagus)', 1),
('悪い', 'わるい', 'warui', 'Buruk', '気分が悪い (Perasaan buruk)', 1),
('暑い', 'あつい', 'atsui', 'Panas', '今日は暑い (Hari ini panas)', 1),
('寒い', 'さむい', 'samui', 'Dingin', '外は寒い (Di luar dingin)', 1),
('美味しい', 'おいしい', 'oishii', 'Enak', '美味しい寿司 (Sushi enak)', 1),
('面白い', 'おもしろい', 'omoshiroi', 'Menarik', '面白い映画 (Film menarik)', 1),
('忙しい', 'いそがしい', 'isogashii', 'Sibuk', '仕事が忙しい (Kerja sibuk)', 1),
('楽しい', 'たのしい', 'tanoshii', 'Menyenangkan', '楽しい旅行 (Liburan menyenangkan)', 1),
('難しい', 'むずかしい', 'muzukashii', 'Sulit', '日本語は難しい (Jepang itu sulit)', 1),
('易しい', 'やさしい', 'yasashii', 'Mudah', '易しい問題 (Soal mudah)', 1),
('好き', 'すき', 'suki', 'Suka', '猫が好き (Suka kucing)', 1),
('嫌い', 'きらい', 'kirai', 'Benci', '虫が嫌い (Benci serangga)', 1),
('上手', 'じょうず', 'jouzu', 'Pintar/Jago', '歌が上手 (Jago nyanyi)', 1),
('下手', 'へた', 'heta', 'Bodoh/Tidak bisa', '絵が下手 (Gak bisa gambar)', 1),
('きれい', 'きれい', 'kirei', 'Cantik/Bersih', 'きれいな花 (Bunga cantik)', 1),
('静か', 'しずか', 'shizuka', 'Tenang', '静かな部屋 (Kamar tenang)', 1),
('元気', 'げんき', 'genki', 'Sehat', '元気ですか (Apa kabar?)', 1),
('有名', 'ゆうめい', 'yuumei', 'Terkenal', '有名な人 (Orang terkenal)', 1),

-- KATA KERJA DASAR (N5)
('食べる', 'たべる', 'taberu', 'Makan', 'ご飯を食べる (Makan nasi)', 1),
('飲む', 'のむ', 'nomu', 'Minum', '水を飲む (Minum air)', 1),
('見る', 'みる', 'miru', 'Melihat', 'テレビを見る (Nonton TV)', 1),
('聞く', 'きく', 'kiku', 'Mendengar', '音楽を聞く (Dengar musik)', 1),
('行く', 'いく', 'iku', 'Pergi', '学校へ行く (Pergi ke sekolah)', 1),
('来る', 'くる', 'kuru', 'Datang', '友達が来る (Teman datang)', 1),
('帰る', 'かえる', 'kaeru', 'Pulang', '家へ帰る (Pulang ke rumah)', 1),
('寝る', 'ねる', 'neru', 'Tidur', '早く寝る (Tidur cepat)', 1),
('起きる', 'おきる', 'okiru', 'Bangun', '6時に起きる (Bangun jam 6)', 1),
('話す', 'はなす', 'hanasu', 'Berbicara', '日本語を話す (Bicara Jepang)', 1),
('書く', 'かく', 'kaku', 'Menulis', '手紙を書く (Nulis surat)', 1),
('読む', 'よむ', 'yomu', 'Membaca', '本を読む (Baca buku)', 1),
('買う', 'かう', 'kau', 'Membeli', '服を買う (Beli baju)', 1),
('する', 'する', 'suru', 'Melakukan', 'スポーツをする (Olahraga)', 1),
('勉強する', 'べんきょうする', 'benkyou suru', 'Belajar', '英語を勉強する (Belajar Inggris)', 1),
('会う', 'あう', 'au', 'Bertemu', '友達に会う (Ketemu teman)', 1),
('洗う', 'あらう', 'arau', 'Mencuci', '手を洗う (Cuci tangan)', 1),
('歩く', 'あるく', 'aruku', 'Berjalan', '駅まで歩く (Jalan ke stasiun)', 1),
('言う', 'いう', 'iu', 'Berkata', '好きだと言う (Bilang suka)', 1),
('泳ぐ', 'およぐ', 'oyogu', 'Berenang', '海で泳ぐ (Renang di laut)', 1),
('売る', 'うる', 'uru', 'Menjual', '家を売る (Jual rumah)', 1),
('置く', 'おく', 'oku', 'Meletakkan', '机に置く (Taruh di meja)', 1),
('押す', 'おす', 'osu', 'Menekan', 'ボタンを押す (Tekan tombol)', 1),
('終わる', 'おわる', 'owaru', 'Selesai', '仕事が終わる (Kerja selesai)', 1),
('貸す', 'かす', 'kasu', 'Meminjamkan', 'ペンを貸す (Pinjamkan pena)', 1),
('借りる', 'かりる', 'kariru', 'Meminjam', '本を借りる (Pinjam buku)', 1),
('消える', 'きえる', 'kieru', 'Padam', '電気が消える (Listrik padam)', 1),
('切る', 'きる', 'kiru', 'Memotong', '紙を切る (Potong kertas)', 1),
('着る', 'きる', 'kiru', 'Memakai (Baju)', 'シャツを着る (Pakai kemeja)', 1),
('困る', 'こまる', 'komaru', 'Susah', 'お金に困る (Susah uang)', 1),
('咲く', 'さく', 'saku', 'Mekar', '花が咲く (Bunga mekar)', 1),
('閉める', 'しめる', 'shimeru', 'Menutup', 'ドアを閉める (Tutup pintu)', 1),
('知る', 'しる', 'shiru', 'Tahu', 'ニュースを知る (Tahu berita)', 1),
('住む', 'すむ', 'sumu', 'Tinggal', '東京に住む (Tinggal di Tokyo)', 1),
('座る', 'すわる', 'suwaru', 'Duduk', '椅子に座る (Duduk di kursi)', 1),
('立つ', 'たつ', 'tatsu', 'Berdiri', 'ここに立つ (Berdiri disini)', 1),
('使う', 'つかう', 'tsukau', 'Menggunakan', 'パソコンを使う (Pakai PC)', 1),
('着く', 'つく', 'tsuku', 'Tiba', '駅に着く (Tiba di stasiun)', 1),
('作る', 'つくる', 'tsukuru', 'Membuat', '料理を作る (Masak)', 1),
('飛ぶ', 'とぶ', 'tobu', 'Terbang', '鳥が飛ぶ (Burung terbang)', 1),
('止まる', 'とまる', 'tomaru', 'Berhenti', '車が止まる (Mobil berhenti)', 1),
('撮る', 'とる', 'toru', 'Memotret', '写真を撮る (Ambil foto)', 1),
('鳴く', 'なく', 'naku', 'Berkicau', '鳥が鳴く (Burung berkicau)', 1),
('並ぶ', 'ならぶ', 'narabu', 'Berbaris', '列に並ぶ (Antre)', 1),
('なる', 'なる', 'naru', 'Menjadi', '医者になる (Jadi dokter)', 1),
('脱ぐ', 'ぬぐ', 'nugu', 'Melepas', '靴を脱ぐ (Lepas sepatu)', 1),
('乗る', 'のる', 'noru', 'Naik', 'バスに乗る (Naik bus)', 1),
('入る', 'はいる', 'hairu', 'Masuk', '部屋に入る (Masuk kamar)', 1),
('走る', 'はしる', 'hashiru', 'Berlari', '速く走る (Lari cepat)', 1),
('待つ', 'まつ', 'matsu', 'Menunggu', 'バスを待つ (Tunggu bus)', 1),
('持つ', 'もつ', 'motsu', 'Memegang', '荷物を持つ (Bawa barang)', 1),
('呼ぶ', 'よぶ', 'yobu', 'Memanggil', 'タクシーを呼ぶ (Panggil taksi)', 1),
('分かる', 'わかる', 'wakaru', 'Mengerti', '意味が分かる (Mengerti arti)', 1),
('忘れる', 'わすれる', 'wasureru', 'Lupa', '宿題を忘れる (Lupa PR)', 1),
('渡す', 'わたす', 'watasu', 'Menyerahkan', '手紙を渡す (Serahkan surat)', 1),
('渡る', 'わたる', 'wataru', 'Menyeberang', '橋を渡る (Seberangi jembatan)', 1),

-- --- POSISI & ARAH (N5 Essential) ---
('上', 'うえ', 'ue', 'Atas', '机の上に本がある (Ada buku di atas meja)', 1),
('下', 'した', 'shita', 'Bawah', '椅子の下に猫がいる (Ada kucing di bawah kursi)', 1),
('前', 'まえ', 'mae', 'Depan', '駅の前に集合 (Kumpul di depan stasiun)', 1),
('後ろ', 'うしろ', 'ushiro', 'Belakang', '私の後ろに立たないで (Jangan berdiri di belakangku)', 1),
('右', 'みぎ', 'migi', 'Kanan', '右に曲がる (Belok kanan)', 1),
('左', 'ひだり', 'hidari', 'Kiri', '左手を使う (Pakai tangan kiri)', 1),
('中', 'なか', 'naka', 'Dalam', '箱の中に何がある？ (Ada apa dalam kotak?)', 1),
('外', 'そと', 'soto', 'Luar', '外で遊ぶ (Main di luar)', 1),
('隣', 'となり', 'tonari', 'Sebelah', '隣の人 (Orang sebelah)', 1),
('近く', 'ちかく', 'chikaku', 'Dekat', '学校の近く (Dekat sekolah)', 1),
('間', 'あいだ', 'aida', 'Antara', 'AとBの間 (Antara A dan B)', 1),
('北', 'きた', 'kita', 'Utara', '北へ行く (Pergi ke utara)', 1),
('南', 'みなみ', 'minami', 'Selatan', '南の島 (Pulau selatan)', 1),
('東', 'ひがし', 'higashi', 'Timur', '太陽は東から昇る (Matahari terbit dari timur)', 1),
('西', 'にし', 'nishi', 'Barat', '西の空 (Langit barat)', 1),
('向こう', 'むこう', 'mukou', 'Sebelah sana/Seberang', '川の向こう (Seberang sungai)', 1),

-- --- WAKTU & TANGGAL (Specific N5) ---
('一昨日', 'おととい', 'ototoi', 'Dua hari lalu', '一昨日は雨でした (Dua hari lalu hujan)', 1),
('明明後日', 'しあさって', 'shiasatte', 'Dua hari lagi', '明明後日会いましょう (Ketemu 2 hari lagi)', 1),
('先週', 'せんしゅう', 'senshuu', 'Minggu lalu', '先週の日曜日 (Minggu lalu)', 1),
('来週', 'らいしゅう', 'raishuu', 'Minggu depan', '来週テストがある (Minggu depan ada tes)', 1),
('今週', 'こんしゅう', 'konshuu', 'Minggu ini', '今週は忙しい (Minggu ini sibuk)', 1),
('先月', 'せんげつ', 'sengetsu', 'Bulan lalu', '先月日本に来ました (Datang ke Jepang bulan lalu)', 1),
('来月', 'らいげつ', 'raigetsu', 'Bulan depan', '来月帰国します (Bulan depan pulang)', 1),
('今月', 'こんげつ', 'kongetsu', 'Bulan ini', '今月の予定 (Jadwal bulan ini)', 1),
('去年', 'きょねん', 'kyonen', 'Tahun lalu', '去年卒業しました (Lulus tahun lalu)', 1),
('来年', 'らいねん', 'rainen', 'Tahun depan', '来年結婚します (Tahun depan menikah)', 1),
('今年', 'ことし', 'kotoshi', 'Tahun ini', '今年は2025年 (Tahun ini 2025)', 1),
('毎朝', 'まいあさ', 'maiasa', 'Setiap pagi', '毎朝コーヒーを飲む (Tiap pagi minum kopi)', 1),
('毎晩', 'まいばん', 'maiban', 'Setiap malam', '毎晩テレビを見る (Tiap malam nonton TV)', 1),
('毎週', 'まいしゅう', 'maishuu', 'Setiap minggu', '毎週テニスをする (Tiap minggu main tenis)', 1),
('毎月', 'まいつき', 'maitsuki', 'Setiap bulan', '毎月貯金する (Tiap bulan nabung)', 1),
('毎年', 'まいとし', 'maitoshi', 'Setiap tahun', '毎年旅行する (Tiap tahun liburan)', 1),
('月曜日', 'げつようび', 'getsuyoubi', 'Senin', '月曜日から働く (Kerja mulai senin)', 1),
('火曜日', 'かようび', 'kayoubi', 'Selasa', '火曜日は燃えるゴミ (Selasa sampah bakar)', 1),
('水曜日', 'すいようび', 'suiyoubi', 'Rabu', '水曜日は休み (Rabu libur)', 1),
('木曜日', 'もくようび', 'mokuyoubi', 'Kamis', '木曜日の会議 (Rapat hari Kamis)', 1),
('金曜日', 'きんようび', 'kinyoubi', 'Jumat', '金曜の夜 (Jumat malam)', 1),
('土曜日', 'どようび', 'doyoubi', 'Sabtu', '土曜日はデート (Sabtu kencan)', 1),
('日曜日', 'にちようび', 'nichiyoubi', 'Minggu', '日曜日は寝る (Minggu tidur)', 1),
('一日', 'ついたち', 'tsuitachi', 'Tanggal 1', '一日は映画の日 (Tanggal 1 hari film)', 1),
('二日', 'ふつか', 'futsuka', 'Tanggal 2 / 2 Hari', '二日酔い (Mabuk 2 hari)', 1),
('三日', 'みっか', 'mikka', 'Tanggal 3 / 3 Hari', '三日月の夜 (Malam bulan sabit)', 1),
('四日', 'よっか', 'yokka', 'Tanggal 4 / 4 Hari', '四日かかる (Butuh 4 hari)', 1),
('五日', 'いつか', 'itsuka', 'Tanggal 5 / 5 Hari', '五日後に会う (Ketemu 5 hari lagi)', 1),
('六日', 'むいか', 'muika', 'Tanggal 6 / 6 Hari', '六日働いた (Kerja 6 hari)', 1),
('七日', 'なのか', 'nanoka', 'Tanggal 7 / 7 Hari', '七日目の蝉 (Jangkrik hari ke-7)', 1),
('八日', 'ようか', 'youka', 'Tanggal 8 / 8 Hari', '八日市場 (Pasar tgl 8)', 1),
('九日', 'ここのか', 'kokonoka', 'Tanggal 9 / 9 Hari', '九日待った (Menunggu 9 hari)', 1),
('十日', 'とおか', 'tooka', 'Tanggal 10 / 10 Hari', '十日町 (Kota Tokamachi)', 1),
('二十日', 'はつか', 'hatsuka', 'Tanggal 20', '二十日大根 (Lobak 20 hari)', 1),

-- --- WARNA (N5) ---
('色', 'いろ', 'iro', 'Warna', '何色が好き？ (Suka warna apa?)', 1),
('赤', 'あか', 'aka', 'Merah', '赤いリンゴ (Apel merah)', 1),
('青', 'あお', 'ao', 'Biru', '青い海 (Laut biru)', 1),
('白', 'しろ', 'shiro', 'Putih', '白い雪 (Salju putih)', 1),
('黒', 'くろ', 'kuro', 'Hitam', '黒い猫 (Kucing hitam)', 1),
('黄色', 'きいろ', 'kiiro', 'Kuning', '黄色い花 (Bunga kuning)', 1),
('茶色', 'ちゃいろ', 'chairo', 'Cokelat', '茶色の靴 (Sepatu cokelat)', 1),
('緑', 'みどり', 'midori', 'Hijau', '緑の木 (Pohon hijau)', 1),

-- --- ANGGOTA TUBUH (N5) ---
('体', 'からだ', 'karada', 'Tubuh/Badan', '体が丈夫 (Badan kuat)', 1),
('頭', 'あたま', 'atama', 'Kepala', '頭がいい (Pintar)', 1),
('顔', 'かお', 'kao', 'Wajah', '顔を洗う (Cuci muka)', 1),
('目', 'め', 'me', 'Mata', '目が悪い (Mata buruk/rabun)', 1),
('耳', 'みみ', 'mimi', 'Telinga', '耳が痛い (Sakit telinga)', 1),
('鼻', 'はな', 'hana', 'Hidung', '鼻が高い (Hidung mancung/Sombong)', 1),
('口', 'くち', 'kuchi', 'Mulut', '口を開ける (Buka mulut)', 1),
('歯', 'は', 'ha', 'Gigi', '歯を磨く (Sikat gigi)', 1),
('手', 'て', 'te', 'Tangan', '手を繋ぐ (Gandengan tangan)', 1),
('足', 'あし', 'ashi', 'Kaki', '足が速い (Lari cepat)', 1),
('背', 'せ', 'se', 'Punggung/Tinggi badan', '背が高い (Badan tinggi)', 1),
('髪', 'かみ', 'kami', 'Rambut', '髪を切る (Potong rambut)', 1),
('指', 'ゆび', 'yubi', 'Jari', '指輪 (Cincin)', 1),

-- --- SATUAN HITUNG (COUNTERS N5) ---
('一つ', 'ひとつ', 'hitotsu', 'Satu buah', '一つください (Minta satu)', 1),
('二つ', 'ふたつ', 'futatsu', 'Dua buah', '二つ目の角 (Belokan kedua)', 1),
('三つ', 'みっつ', 'mittsu', 'Tiga buah', '三つのお願い (Tiga permintaan)', 1),
('四つ', 'よっつ', 'yottsu', 'Empat buah', '四つ葉のクローバー (Semanggi daun 4)', 1),
('五つ', 'いつつ', 'itsutsu', 'Lima buah', '星が五つ (Bintang lima)', 1),
('六つ', 'むっつ', 'muttsu', 'Enam buah', '六つ子 (Kembar enam)', 1),
('七つ', 'ななつ', 'nanatsu', 'Tujuh buah', '七つの海 (Tujuh samudra)', 1),
('八つ', 'やっつ', 'yattsu', 'Delapan buah', 'おやつ (Camilan/Jam 8)', 1),
('九つ', 'ここのつ', 'kokonotsu', 'Sembilan buah', '九つの命 (Sembilan nyawa)', 1),
('十', 'とお', 'too', 'Sepuluh buah', '十人十色 (Beda orang beda sifat)', 1),
('何人', 'なんにん', 'nannin', 'Berapa orang', '家族は何人ですか (Keluarga berapa orang?)', 1),
('何枚', 'なんまい', 'nanmai', 'Berapa lembar', '紙は何枚？ (Kertas berapa lembar?)', 1),
('何回', 'なんかい', 'nankai', 'Berapa kali', '何回も言った (Sudah bilang berkali-kali)', 1),
('何個', 'なんこ', 'nanko', 'Berapa buah (kecil)', 'リンゴは何個？ (Apel berapa?)', 1),
('何本', 'なんぼん', 'nanbon', 'Berapa batang', 'ペンは何本？ (Pena berapa?)', 1),
('何時', 'なんじ', 'nanji', 'Jam berapa', '今何時ですか (Sekarang jam berapa?)', 1),
('何分', 'なんぷん', 'nanpun', 'Berapa menit', 'あと何分？ (Sisa berapa menit?)', 1),
('半分', 'はんぶん', 'hanbun', 'Setengah', '半分こしよう (Bagi setengah)', 1),

-- --- ALAM (NATURE N5) ---
('空', 'そら', 'sora', 'Langit', '青い空 (Langit biru)', 1),
('山', 'やま', 'yama', 'Gunung', '富士山 (Gunung Fuji)', 1),
('川', 'かわ', 'kawa', 'Sungai', '川で泳ぐ (Renang di sungai)', 1),
('海', 'うみ', 'umi', 'Laut', '海に行く (Pergi ke laut)', 1),
('雨', 'あめ', 'ame', 'Hujan', '雨が降る (Turun hujan)', 1),
('雪', 'ゆき', 'yuki', 'Salju', '雪だるま (Boneka salju)', 1),
('風', 'かぜ', 'kaze', 'Angin', '風が強い (Angin kencang)', 1),
('晴れ', 'はれ', 'hare', 'Cerah', '明日は晴れ (Besok cerah)', 1),
('曇り', 'くもり', 'kumori', 'Mendung', '曇りのち雨 (Mendung lalu hujan)', 1),
('花', 'はな', 'hana', 'Bunga', '花見 (Melihat bunga)', 1),
('木', 'き', 'ki', 'Pohon/Kayu', '木に登る (Manjat pohon)', 1),
('犬', 'いぬ', 'inu', 'Anjing', '犬の散歩 (Jalan-jalan anjing)', 1),
('猫', 'ねこ', 'neko', 'Kucing', '猫が好き (Suka kucing)', 1),
('鳥', 'とり', 'tori', 'Burung', '焼き鳥 (Sate ayam)', 1),

-- --- PAKAIAN & AKSESORIS (N5) ---
('服', 'ふく', 'fuku', 'Baju', '服を着る (Pakai baju)', 1),
('洋服', 'ようふく', 'youfuku', 'Pakaian Barat', '洋服を買う (Beli pakaian)', 1),
('着物', 'きもの', 'kimono', 'Kimono', '着物を着る (Pakai kimono)', 1),
('シャツ', 'しゃつ', 'shatsu', 'Kemeja', '白いシャツ (Kemeja putih)', 1),
('セーター', 'せーたー', 'seetaa', 'Sweater', 'ウールのセーター (Sweater wol)', 1),
('コート', 'こーと', 'kooto', 'Mantel', 'コートを脱ぐ (Lepas mantel)', 1),
('ズボン', 'ずぼん', 'zubon', 'Celana Panjang', 'ズボンをはく (Pakai celana)', 1),
('スカート', 'すかーと', 'sukaato', 'Rok', 'スカートをはく (Pakai rok)', 1),
('靴', 'くつ', 'kutsu', 'Sepatu', '靴をはく (Pakai sepatu)', 1),
('靴下', 'くつした', 'kutsushita', 'Kaos kaki', '靴下をはく (Pakai kaos kaki)', 1),
('帽子', 'ぼうし', 'boushi', 'Topi', '帽子をかぶる (Pakai topi)', 1),
('眼鏡', 'めがね', 'megane', 'Kacamata', '眼鏡をかける (Pakai kacamata)', 1),
('ネクタイ', 'ねくたい', 'nekutai', 'Dasi', 'ネクタイをしめる (Pakai dasi)', 1),
('財布', 'さいふ', 'saifu', 'Dompet', '財布を忘れた (Lupa dompet)', 1),

-- --- BENDA DI RUMAH/SEKOLAH (N5) ---
('机', 'つくえ', 'tsukue', 'Meja Tulis', '机に向かう (Menghadap meja)', 1),
('椅子', 'いす', 'isu', 'Kursi', '椅子に座る (Duduk di kursi)', 1),
('テーブル', 'てーぶる', 'teeburu', 'Meja Makan', 'テーブルを拭く (Lap meja)', 1),
('ベッド', 'べっど', 'beddo', 'Kasur', 'ベッドで寝る (Tidur di kasur)', 1),
('テレビ', 'てれび', 'terebi', 'Televisi', 'テレビを見る (Nonton TV)', 1),
('ラジオ', 'らじお', 'rajio', 'Radio', 'ラジオ体操 (Senam radio)', 1),
('カメラ', 'かめら', 'kamera', 'Kamera', 'カメラで撮る (Potret pakai kamera)', 1),
('コンピューター', 'こんぴゅーたー', 'konpyuutaa', 'Komputer', 'コンピューターを使う (Pakai komputer)', 1),
('電話', 'でんわ', 'denwa', 'Telepon', '電話が鳴る (Telepon bunyi)', 1),
('手紙', 'てがみ', 'tegami', 'Surat', '手紙を書く (Tulis surat)', 1),
('切手', 'きって', 'kitte', 'Prangko', '切手を貼る (Tempel prangko)', 1),
('封筒', 'ふうとう', 'fuutou', 'Amplop', '封筒に入れる (Masukan amplop)', 1),
('鉛筆', 'えんぴつ', 'enpitsu', 'Pensil', '鉛筆削り (Rautan pensil)', 1),
('ボールペン', 'ぼーるぺん', 'boorupen', 'Pulpen', '赤のボールペン (Pulpen merah)', 1),
('万年筆', 'まんねんひつ', 'mannenhitsu', 'Pena Fountain', '万年筆で書く (Tulis pakai fountain pen)', 1),
('ノート', 'のーと', 'nooto', 'Buku Catatan', 'ノートを取る (Mencatat)', 1),
('ページ', 'ぺーじ', 'peeji', 'Halaman', '次のページ (Halaman berikutnya)', 1),
('カレンダー', 'かれんだー', 'karendaa', 'Kalender', 'カレンダーを見る (Lihat kalender)', 1),
('箱', 'はこ', 'hako', 'Kotak', '箱を開ける (Buka kotak)', 1),
('鍵', 'かぎ', 'kagi', 'Kunci', '鍵をかける (Mengunci)', 1),
('石鹸', 'せっけん', 'sekken', 'Sabun', '石鹸で洗う (Cuci pakai sabun)', 1),
('タオル', 'たおる', 'taoru', 'Handuk', 'タオルで拭く (Lap pakai handuk)', 1),
('お皿', 'おさら', 'osara', 'Piring', 'お皿を洗う (Cuci piring)', 1),
('箸', 'はし', 'hashi', 'Sumpit', '箸を使う (Pakai sumpit)', 1),
('スプーン', 'すぷーん', 'supuun', 'Sendok', 'スプーン一杯 (Satu sendok)', 1),
('フォーク', 'ふぉーく', 'fooku', 'Garpu', 'フォークとナイフ (Garpu dan pisau)', 1),
('ナイフ', 'ないふ', 'naifu', 'Pisau', 'ナイフで切る (Potong pakai pisau)', 1),
('コップ', 'こっぷ', 'koppu', 'Gelas', 'コップ一杯の水 (Segelas air)', 1),
('マッチ', 'まっち', 'macchi', 'Korek Api', 'マッチを擦る (Nyalakan korek)', 1),
('ライター', 'らいたー', 'raitaa', 'Korek Gas', 'ライターを借りる (Pinjam korek gas)', 1),
('灰皿', 'はいざら', 'haizara', 'Asbak', '灰皿をください (Minta asbak)', 1),
('冷蔵庫', 'れいぞうこ', 'reizouko', 'Kulkas', '冷蔵庫に入れる (Masukan kulkas)', 1),
('洗濯機', 'せんたくき', 'sentakuki', 'Mesin Cuci', '洗濯機を回す (Nyalakan mesin cuci)', 1),
('掃除機', 'そうじき', 'soujiki', 'Vacuum Cleaner', '掃除機をかける (Sedot debu)', 1),

-- --- MAKANAN & MINUMAN (Specific N5) ---
('ご飯', 'ごはん', 'gohan', 'Nasi/Makan', '朝ごはん (Sarapan)', 1),
('パン', 'ぱん', 'pan', 'Roti', 'パン屋 (Toko roti)', 1),
('肉', 'にく', 'niku', 'Daging', '牛肉 (Daging sapi)', 1),
('魚', 'さかな', 'sakana', 'Ikan', '魚釣り (Mancing ikan)', 1),
('卵', 'たまご', 'tamago', 'Telur', '卵焼き (Telur dadar)', 1),
('野菜', 'やさい', 'yasai', 'Sayuran', '野菜ジュース (Jus sayur)', 1),
('果物', 'くだもの', 'kudamono', 'Buah-buahan', '果物を切る (Potong buah)', 1),
('水', 'みず', 'mizu', 'Air', '水を飲む (Minum air)', 1),
('お茶', 'おちゃ', 'ocha', 'Teh Jepang', 'お茶を入れる (Seduh teh)', 1),
('紅茶', 'こうちゃ', 'koucha', 'Teh Hitam', '紅茶にミルク (Teh susu)', 1),
('牛乳', 'ぎゅうにゅう', 'gyuunyuu', 'Susu Sapi', '牛乳を飲む (Minum susu)', 1),
('ミルク', 'みるく', 'miruku', 'Susu', 'ホットミルク (Susu panas)', 1),
('ジュース', 'じゅーす', 'juusu', 'Jus', 'オレンジジュース (Jus jeruk)', 1),
('ビール', 'びーる', 'biiru', 'Bir', 'ビールを飲む (Minum bir)', 1),
('お酒', 'おさけ', 'osake', 'Alkohol/Sake', 'お酒に酔う (Mabuk)', 1),
('料理', 'りょうり', 'ryouri', 'Masakan', '日本料理 (Masakan Jepang)', 1),
('弁当', 'べんとう', 'bentou', 'Bekal', 'お弁当箱 (Kotak bekal)', 1),
('砂糖', 'さとう', 'satou', 'Gula', '砂糖を入れる (Tambah gula)', 1),
('塩', 'しお', 'shio', 'Garam', '塩辛い (Asin)', 1),
('醤油', 'しょうゆ', 'shouyu', 'Kecap Asin', '醤油をつける (Celup kecap asin)', 1),
('バター', 'ばたー', 'bataa', 'Mentega', 'バターを塗る (Oles mentega)', 1),
('カレー', 'かれー', 'karee', 'Kari', 'カレーライス (Nasi kari)', 1),
('ラーメン', 'らーめん', 'raamen', 'Ramen', 'ラーメン屋 (Kedai ramen)', 1),
('喫茶店', 'きっさてん', 'kissaten', 'Kafe', '喫茶店で休む (Istirahat di kafe)', 1),

-- --- KATA KERJA (Additional N5) ---
('あります', 'あります', 'arimasu', 'Ada (Benda)', '本があります (Ada buku)', 1),
('います', 'います', 'imasu', 'Ada (Makhluk)', '猫がいます (Ada kucing)', 1),
('あげる', 'あげる', 'ageru', 'Memberi', 'プレゼントをあげる (Memberi kado)', 1),
('もらう', 'もらう', 'morau', 'Menerima', '手紙をもらう (Terima surat)', 1),
('借りる', 'かりる', 'kariru', 'Meminjam', 'お金を借りる (Pinjam uang)', 1),
('貸す', 'かす', 'kasu', 'Meminjamkan', '本を貸す (Pinjamkan buku)', 1),
('教える', 'おしえる', 'oshieru', 'Mengajar/Beritahu', '住所を教える (Beritahu alamat)', 1),
('習う', 'ならう', 'narau', 'Belajar (dari orang)', 'ピアノを習う (Les piano)', 1),
('かける', 'かける', 'kakeru', 'Menelepon', '電話をかける (Menelepon)', 1),
('開ける', 'あける', 'akeru', 'Membuka', 'ドアを開ける (Buka pintu)', 1),
('閉める', 'しめる', 'shimeru', 'Menutup', '窓を閉める (Tutup jendela)', 1),
('つける', 'つける', 'tsukeru', 'Menyalakan', '電気をつける (Nyalakan lampu)', 1),
('消す', 'けす', 'kesu', 'Mematikan/Hapus', 'テレビを消す (Matikan TV)', 1),
('働く', 'はたらく', 'hataraku', 'Bekerja', '銀行で働く (Kerja di bank)', 1),
('休みます', 'やすみます', 'yasumimasu', 'Istirahat/Libur', '学校を休みます (Libur sekolah)', 1),
('散歩する', 'さんぽする', 'sanposuru', 'Jalan-jalan', '公園を散歩する (Jalan di taman)', 1),
('結婚する', 'けっこんする', 'kekkonsuru', 'Menikah', '来年結婚する (Menikah tahun depan)', 1),
('買い物する', 'かいものする', 'kaimonosuru', 'Berbelanja', 'デパートで買い物 (Belanja di mall)', 1),
('掃除する', 'そうじする', 'soujisuru', 'Membersihkan', '部屋を掃除する (Bersihkan kamar)', 1),
('洗濯する', 'せんたくする', 'sentakusuru', 'Mencuci baju', '服を洗濯する (Cuci baju)', 1),
('勉強する', 'べんきょうする', 'benkyousuru', 'Belajar', '日本語を勉強する (Belajar Jepang)', 1),
('練習する', 'れんしゅうする', 'renshuusuru', 'Berlatih', '歌を練習する (Latihan nyanyi)', 1),
('質問する', 'しつもんする', 'shitsumonsuru', 'Bertanya', '先生に質問する (Tanya guru)', 1),
('渡る', 'わたる', 'wataru', 'Menyeberang', '道を渡る (Seberang jalan)', 1),
('曲がる', 'まがる', 'magaru', 'Belok', '右へ曲がる (Belok kanan)', 1),
('乗る', 'のる', 'noru', 'Naik (kendaraan)', 'バスに乗る (Naik bus)', 1),
('降りる', 'おりる', 'oriru', 'Turun (kendaraan)', '電車を降りる (Turun kereta)', 1),
('出かける', 'でかける', 'dekakeru', 'Pergi keluar', '遊びに出かける (Pergi main)', 1),
('入る', 'はいる', 'hairu', 'Masuk', 'お風呂に入る (Masuk bak mandi)', 1),
('出る', 'でる', 'deru', 'Keluar', '家を出る (Keluar rumah)', 1),
('座る', 'すわる', 'suwaru', 'Duduk', 'ここに座る (Duduk sini)', 1),
('立つ', 'たつ', 'tatsu', 'Berdiri', '席を立つ (Berdiri dari kursi)', 1),
('脱ぐ', 'ぬぐ', 'nugu', 'Melepas', '靴を脱ぐ (Lepas sepatu)', 1),
('置く', 'おく', 'oku', 'Meletakkan', 'カバンを置く (Taruh tas)', 1),
('住む', 'すむ', 'sumu', 'Tinggal', '東京に住む (Tinggal di Tokyo)', 1),
('知る', 'しる', 'shiru', 'Tahu/Kenal', '名前を知っている (Tahu namanya)', 1),
('要る', 'いる', 'iru', 'Perlu', 'ビザが要る (Perlu visa)', 1),
('売る', 'うる', 'uru', 'Menjual', '切符を売る (Jual tiket)', 1),
('呼ぶ', 'よぶ', 'yobu', 'Memanggil', 'タクシーを呼ぶ (Panggil taksi)', 1),
('止まる', 'とまる', 'tomaru', 'Berhenti', '車が止まる (Mobil berhenti)', 1),
('見せる', 'みせる', 'miseru', 'Memperlihatkan', '写真を見せる (Tunjukan foto)', 1),
('忘れる', 'わすれる', 'wasureru', 'Lupa', '宿題を忘れる (Lupa PR)', 1),
('困る', 'こまる', 'komaru', 'Susah/Masalah', '道に迷って困る (Susah karena tersesat)', 1),
('疲れる', 'つかれる', 'tsukareru', 'Lelah', '歩いて疲れる (Lelah berjalan)', 1),
('晴れる', 'はれる', 'hareru', 'Cerah', '明日は晴れる (Besok cerah)', 1),
('曇る', 'くもる', 'kumoru', 'Mendung', '空が曇る (Langit mendung)', 1),
('降る', 'ふる', 'furu', 'Turun (hujan)', '雨が降る (Turun hujan)', 1),
('吹く', 'ふく', 'fuku', 'Bertiup', '風が吹く (Angin bertiup)', 1),
('鳴く', 'なく', 'naku', 'Berkicau/Bunyi', '鳥が鳴く (Burung berkicau)', 1),
('死ぬ', 'しぬ', 'shinu', 'Mati', '花が死ぬ (Bunga mati)', 1),
('並ぶ', 'ならぶ', 'narabu', 'Berbaris', '列に並ぶ (Antre)', 1),
('並べる', 'ならべる', 'naraberu', 'Menjejerkan', '椅子を並べる (Jejerkan kursi)', 1),
('渡す', 'わたす', 'watasu', 'Menyerahkan', '塩を渡す (Oper garam)', 1),
('撮る', 'とる', 'toru', 'Memotret', '写真を撮る (Ambil foto)', 1),
('引く', 'ひく', 'hiku', 'Menarik', '辞書を引く (Cari di kamus)', 1),
('弾く', 'ひく', 'hiku', 'Bermain alat musik', 'ギターを弾く (Main gitar)', 1),
('吸う', 'すう', 'suu', 'Menghisap/Merokok', 'タバコを吸う (Merokok)', 1),
('登る', 'のぼる', 'noboru', 'Mendaki', '山に登る (Naik gunung)', 1),
('勤める', 'つとめる', 'tsutomeru', 'Bekerja (di)', '会社に勤める (Kerja di PT)', 1),
('張る', 'はる', 'haru', 'Menempel', 'ポスターを張る (Tempel poster)', 1),
('磨く', 'みがく', 'migaku', 'Menggosok', '靴を磨く (Semir sepatu)', 1),
('洗う', 'あらう', 'arau', 'Mencuci', '皿を洗う (Cuci piring)', 1),

-- --- KATA SIFAT (Adjectives N5) ---
('広い', 'ひろい', 'hiroi', 'Luas', '広い部屋 (Kamar luas)', 1),
('狭い', 'せまい', 'semai', 'Sempit', '狭い道 (Jalan sempit)', 1),
('高い', 'たかい', 'takai', 'Tinggi/Mahal', '背が高い (Badan tinggi)', 1),
('低い', 'ひくい', 'hikui', 'Rendah', '背が低い (Pendek)', 1),
('新しい', 'あたらしい', 'atarashii', 'Baru', '新しい車 (Mobil baru)', 1),
('古い', 'ふるい', 'furui', 'Lama/Tua', '古い本 (Buku lama)', 1),
('多い', 'おおい', 'ooi', 'Banyak', '人が多い (Banyak orang)', 1),
('少ない', 'すくない', 'sukunai', 'Sedikit', 'お金が少ない (Uang sedikit)', 1),
('大きい', 'おおきい', 'ookii', 'Besar', '大きな声 (Suara besar)', 1),
('小さい', 'ちいさい', 'chiisai', 'Kecil', '小さな夢 (Mimpi kecil)', 1),
('遠い', 'とおい', 'tooi', 'Jauh', '駅が遠い (Stasiun jauh)', 1),
('近い', 'ちかい', 'chikai', 'Dekat', '家から近い (Dekat rumah)', 1),
('暑い', 'あつい', 'atsui', 'Panas (Cuaca)', '今日は暑い (Hari ini panas)', 1),
('寒い', 'さむい', 'samui', 'Dingin (Cuaca)', '冬は寒い (Musim dingin itu dingin)', 1),
('熱い', 'あつい', 'atsui', 'Panas (Benda)', '熱いお茶 (Teh panas)', 1),
('冷たい', 'つめたい', 'tsumetai', 'Dingin (Benda)', '冷たい水 (Air dingin)', 1),
('良い', 'よい', 'yoi', 'Bagus', '良い考え (Ide bagus)', 1),
('悪い', 'わるい', 'warui', 'Buruk', '頭が悪い (Bodoh)', 1),
('面白い', 'おもしろい', 'omoshiroi', 'Menarik/Lucu', '面白い本 (Buku menarik)', 1),
('つまらない', 'つまらない', 'tsumaranai', 'Membosankan', 'つまらない映画 (Film bosan)', 1),
('美味しい', 'おいしい', 'oishii', 'Enak', '美味しい料理 (Masakan enak)', 1),
('不味い', 'まずい', 'mazui', 'Tidak enak', 'まずい水 (Air tak enak)', 1),
('甘い', 'あまい', 'amai', 'Manis', '甘いケーキ (Kue manis)', 1),
('辛い', 'からい', 'karai', 'Pedas', '辛いカレー (Kari pedas)', 1),
('忙しい', 'いそがしい', 'isogashii', 'Sibuk', '毎日忙しい (Tiap hari sibuk)', 1),
('暇', 'ひま', 'hima', 'Senggang', '暇な時間 (Waktu luang)', 1),
('早い', 'はやい', 'hayai', 'Cepat (Waktu)', '朝が早い (Pagi buta)', 1),
('速い', 'はやい', 'hayai', 'Cepat (Kecepatan)', '足が速い (Lari cepat)', 1),
('遅い', 'おそい', 'osoi', 'Lambat', '歩くのが遅い (Jalan lambat)', 1),
('長い', 'ながい', 'nagai', 'Panjang', '長い髪 (Rambut panjang)', 1),
('短い', 'みじかい', 'mijikai', 'Pendek', '短いスカート (Rok pendek)', 1),
('明るい', 'あかるい', 'akarui', 'Terang/Ceria', '明るい部屋 (Kamar terang)', 1),
('暗い', 'くらい', 'kurai', 'Gelap', '暗い道 (Jalan gelap)', 1),
('重い', 'おもい', 'omoi', 'Berat', '重い荷物 (Barang berat)', 1),
('軽い', 'かるい', 'karui', 'Ringan', '軽い靴 (Sepatu ringan)', 1),
('強い', 'つよい', 'tsuyoi', 'Kuat', '強い風 (Angin kencang)', 1),
('弱い', 'よわい', 'yowai', 'Lemah', '体が弱い (Badan lemah)', 1),
('太い', 'ふとい', 'futoi', 'Tebal/Gemuk', '太い足 (Kaki gemuk)', 1),
('細い', 'ほそい', 'hosoi', 'Tipis/Langsing', '細い線 (Garis tipis)', 1),
('若', 'わかい', 'wakai', 'Muda', '若い先生 (Guru muda)', 1),
('好き', 'すき', 'suki', 'Suka', '日本が好き (Suka Jepang)', 1),
('嫌い', 'きらい', 'kirai', 'Benci', '魚が嫌い (Benci ikan)', 1),
('上手', 'じょうず', 'jouzu', 'Pandai', '絵が上手 (Pandai gambar)', 1),
('下手', 'へた', 'heta', 'Tidak pandai', '字が下手 (Tulisan jelek)', 1),
('きれい', 'きれい', 'kirei', 'Cantik/Bersih', 'きれいな海 (Laut bersih)', 1),
('静か', 'しずか', 'shizuka', 'Tenang', '静かな町 (Kota tenang)', 1),
('賑やか', 'にぎやか', 'nigiyaka', 'Ramai', '賑やかな通り (Jalan ramai)', 1),
('有名', 'ゆうめい', 'yuumei', 'Terkenal', '有名な店 (Toko terkenal)', 1),
('親切', 'しんせつ', 'shinsetsu', 'Ramah/Baik', '親切な人 (Orang baik)', 1),
('元気', 'げんき', 'genki', 'Sehat', '元気な子供 (Anak sehat)', 1),
('便利', 'べんり', 'benri', 'Praktis', '便利な道具 (Alat praktis)', 1),
('大切', 'たいせつ', 'taisetsu', 'Penting', '大切な人 (Orang penting)', 1),
('大丈夫', 'だいじょうぶ', 'daijoubu', 'Tidak apa-apa', '大丈夫ですか (Apa anda oke?)', 1),
('色々', 'いろいろ', 'iroiro', 'Macam-macam', '色々な花 (Macam2 bunga)', 1),
('大変', 'たいへん', 'taihen', 'Berat/Susah', '大変な仕事 (Kerja berat)', 1),
('簡単', 'かんたん', 'kantan', 'Mudah', '簡単なテスト (Tes mudah)', 1),
('欲しい', 'ほしい', 'hoshii', 'Ingin', '車が欲しい (Ingin mobil)', 1),
('痛い', 'いたい', 'itai', 'Sakit', '頭が痛い (Sakit kepala)', 1),
('汚い', 'きたない', 'kitanai', 'Kotor', '汚い手 (Tangan kotor)', 1),
('危ない', 'あぶない', 'abunai', 'Bahaya', '危ないよ (Awas bahaya!)', 1),

----- Immediate/N4 Voacabs -----
-- KATA KERJA N4
('謝る', 'あやまる', 'ayamaru', 'Meminta maaf', '素直に謝る (Minta maaf tulus)', 2),
('急ぐ', 'いそぐ', 'isogu', 'Buru-buru', '急いでください (Tolong buru-buru)', 2),
('祈る', 'いのる', 'inoru', 'Berdoa', '平和を祈る (Berdoa perdamaian)', 2),
('植える', 'うえる', 'ueru', 'Menanam', '木を植える (Tanam pohon)', 2),
('選ぶ', 'えらぶ', 'erabu', 'Memilih', 'これを選ぶ (Pilih ini)', 2),
('遅れる', 'おくれる', 'okureru', 'Terlambat', '電車に遅れる (Telat kereta)', 2),
('怒る', 'おこる', 'okoru', 'Marah', '父が怒る (Ayah marah)', 2),
('落ちる', 'おちる', 'ochiru', 'Jatuh', '葉が落ちる (Daun jatuh)', 2),
('落とす', 'おとす', 'otosu', 'Menjatuhkan', 'ペンを落とす (Jatuhkan pena)', 2),
('踊る', 'おどる', 'odoru', 'Menari', 'ダンスを踊る (Menari)', 2),
('驚く', 'おどろく', 'odoroku', 'Terkejut', '音に驚く (Kaget suara)', 2),
('飾る', 'かざる', 'kazaru', 'Menghias', '部屋を飾る (Hias kamar)', 2),
('片付ける', 'かたづける', 'katazukeru', 'Membereskan', '部屋を片付ける (Bereskan kamar)', 2),
('乾く', 'かわく', 'kawaku', 'Kering', '服が乾く (Baju kering)', 2),
('変わる', 'かわる', 'kawaru', 'Berubah', '色が変わる (Warna berubah)', 2),
('決める', 'きめる', 'kimeru', 'Memutuskan', '進路を決める (Putuskan masa depan)', 2),
('比べる', 'くらべる', 'kuraberu', 'Membandingkan', '背を比べる (Bandingkan tinggi)', 2),
('暮らす', 'くらす', 'kurasu', 'Hidup', '一人で暮らす (Hidup sendiri)', 2),
('混む', 'こむ', 'komu', 'Macet', '道が混む (Jalan macet)', 2),
('壊す', 'こわす', 'kowasu', 'Merusak', '物を壊す (Rusak barang)', 2),
('壊れる', 'こわれる', 'kowareru', 'Rusak', '椅子が壊れる (Kursi rusak)', 2),
('探す', 'さがす', 'sagasu', 'Mencari', '鍵を探す (Cari kunci)', 2),
('下がる', 'さがる', 'sagaru', 'Turun', '熱が下がる (Demam turun)', 2),
('下げる', 'さげる', 'sageru', 'Menurunkan', '頭を下げる (Tunduk kepala)', 2),
('騒ぐ', 'さわぐ', 'sawagu', 'Berisik', '教室で騒ぐ (Berisik di kelas)', 2),
('触る', 'さわる', 'sawaru', 'Menyentuh', '犬に触る (Sentuh anjing)', 2),
('叱る', 'しかる', 'shikaru', 'Memarahi', '子供を叱る (Marahi anak)', 2),
('調べる', 'しらべる', 'shiraberu', 'Memeriksa', '辞書で調べる (Cek kamus)', 2),
('知らせる', 'しらせる', 'shiraseru', 'Memberitahu', 'ニュースを知らせる (Beri kabar)', 2),
('過ぎる', 'すぎる', 'sugiru', 'Melewati', '時間が過ぎる (Waktu lewat)', 2),
('進む', 'すすむ', 'susumu', 'Maju', '前へ進む (Maju depan)', 2),
('捨てる', 'すてる', 'suteru', 'Membuang', 'ゴミを捨てる (Buang sampah)', 2),
('滑る', 'すべる', 'suberu', 'Terpeleset', '氷で滑る (Peleset di es)', 2),
('育てる', 'そだてる', 'sodateru', 'Membesarkan', '花を育てる (Rawat bunga)', 2),
('倒れる', 'たおれる', 'taoreru', 'Roboh', '木が倒れる (Pohon roboh)', 2),
('足す', 'たす', 'tasu', 'Menambah', '水を足す (Tambah air)', 2),
('訪ねる', 'たずねる', 'tazuneru', 'Berkunjung', '家を訪ねる (Berkunjung ke rumah)', 2),
('建てる', 'たてる', 'tateru', 'Membangun', '家を建てる (Bangun rumah)', 2),
('楽しむ', 'たのしむ', 'tanoshimu', 'Menikmati', '生活を楽しむ (Nikmati hidup)', 2),
('足りる', 'たりる', 'tariru', 'Cukup', 'お金が足りる (Uang cukup)', 2),
('捕まえる', 'つかまえる', 'tsukamaeru', 'Menangkap', '泥棒を捕まえる (Tangkap maling)', 2),
('疲れる', 'つかれる', 'tsukareru', 'Lelah', '仕事で疲れる (Lelah kerja)', 2),
('付く', 'つく', 'tsuku', 'Menempel', '埃が付く (Debu nempel)', 2),
('伝える', 'つたえる', 'tsutaeru', 'Menyampaikan', '気持ちを伝える (Sampaikan rasa)', 2),
('続く', 'つづく', 'tsuzuku', 'Berlanjut', '雨が続く (Hujan lanjut)', 2),
('続ける', 'つづける', 'tsuzukeru', 'Melanjutkan', '勉強を続ける (Lanjut belajar)', 2),
('包む', 'つつむ', 'tsutsumu', 'Membungkus', '紙で包む (Bungkus kertas)', 2),
('釣る', 'つる', 'tsuru', 'Memancing', '魚を釣る (Mancing ikan)', 2),
('手伝う', 'てつだう', 'tetsudau', 'Membantu', '母を手伝う (Bantu ibu)', 2),
('直す', 'なおす', 'naosu', 'Memperbaiki', '時計を直す (Perbaiki jam)', 2),
('治る', 'なおる', 'naoru', 'Sembuh', '病気が治る (Sembuh sakit)', 2),
('亡くなる', 'なくなる', 'nakunaru', 'Meninggal', '祖父が亡くなる (Kakek meninggal)', 2),
('投げる', 'なげる', 'nageru', 'Melempar', 'ボールを投げる (Lempar bola)', 2),
('慣れる', 'なれる', 'nareru', 'Terbiasa', '仕事に慣れる (Biasa kerja)', 2),
('逃げる', 'にげる', 'nigeru', 'Kabur', '速く逃げる (Kabur cepat)', 2),
('似る', 'にる', 'niru', 'Mirip', '母に似る (Mirip ibu)', 2),
('盗む', 'ぬすむ', 'nusumu', 'Mencuri', '金を盗む (Curi uang)', 2),
('塗る', 'ぬる', 'nuru', 'Mengecat', 'ペンキを塗る (Cat tembok)', 2),
('濡れる', 'ぬれる', 'nureru', 'Basah', '雨で濡れる (Basah hujan)', 2),
('残る', 'のこる', 'nokoru', 'Tersisa', '食事が残る (Makanan sisa)', 2),
('運ぶ', 'はこぶ', 'hakobu', 'Mengangkut', '荷物を運ぶ (Angkut barang)', 2),
('始める', 'はじめる', 'hajimeru', 'Memulai', '勉強を始める (Mulai belajar)', 2),
('払う', 'はらう', 'harau', 'Membayar', '代金を払う (Bayar tagihan)', 2),
('冷える', 'ひえる', 'hieru', 'Dingin', '体が冷える (Badan dingin)', 2),
('光る', 'ひかる', 'hikaru', 'Bersinar', '星が光る (Bintang bersinar)', 2),
('増える', 'ふえる', 'fueru', 'Bertambah', '貯金が増える (Tabungan nambah)', 2),
('太る', 'ふとる', 'futoru', 'Gemuk', '最近太る (Baru ini gemuk)', 2),
('踏む', 'ふむ', 'fumu', 'Menginjak', '足を踏む (Injak kaki)', 2),
('褒める', 'ほめる', 'homeru', 'Memuji', '人を褒める (Puji orang)', 2),
('負ける', 'まける', 'makeru', 'Kalah', '試合に負ける (Kalah tanding)', 2),
('間違える', 'まちがえる', 'machigaeru', 'Salah', '道を間違える (Salah jalan)', 2),
('間に合う', 'まにあう', 'maniau', 'Keburu', 'バスに間に合う (Keburu bus)', 2),
('見つかる', 'みつかる', 'mitsukaru', 'Ketemu', '鍵が見つかる (Kunci ketemu)', 2),
('見つける', 'みつける', 'mitsukeru', 'Menemukan', '良い本を見つける (Temukan buku)', 2),
('向かう', 'むかう', 'mukau', 'Menuju', '家へ向かう (Menuju rumah)', 2),
('迎える', 'むかえる', 'mukaeru', 'Menjemput', '客を迎える (Jemput tamu)', 2),
('戻る', 'もどる', 'modoru', 'Kembali', '席に戻る (Kembali duduk)', 2),
('焼く', 'やく', 'yaku', 'Membakar', '肉を焼く (Bakar daging)', 2),
('役に立つ', 'やくにたつ', 'yakunitatsu', 'Berguna', 'この本は役に立つ (Buku ini guna)', 2),
('痩せる', 'やせる', 'yaseru', 'Kurus', '運動して痩せる (Kurus olahraga)', 2),
('止む', 'やむ', 'yamu', 'Berhenti (Hujan)', '雨が止む (Hujan stop)', 2),
('汚れる', 'よごれる', 'yogoreru', 'Kotor', '服が汚れる (Baju kotor)', 2),
('沸かす', 'わかす', 'wakasu', 'Merebus', '湯を沸かす (Rebus air)', 2),
('沸く', 'わく', 'waku', 'Mendidih', '湯が沸く (Air mendidih)', 2),
('割れる', 'われる', 'wareru', 'Pecah', '窓が割れる (Jendela pecah)', 2),

-- KATA BENDA & SIFAT N4
('安全', 'あんぜん', 'anzen', 'Aman', '安全な場所 (Tempat aman)', 2),
('丁寧', 'ていねい', 'teinei', 'Sopan', '丁寧な言葉 (Kata sopan)', 2),
('危険', 'きけん', 'kiken', 'Bahaya', '危険な作業 (Kerja bahaya)', 2),
('残念', 'ざんねん', 'zannen', 'Sayang sekali', '残念な結果 (Hasil sayang)', 2),
('心配', 'しんぱい', 'shinpai', 'Khawatir', '親の心配 (Khawatir ortu)', 2),
('自由', 'じゆう', 'jiyuu', 'Bebas', '自由な時間 (Waktu bebas)', 2),
('十分', 'じゅうぶん', 'juubun', 'Cukup', '十分な睡眠 (Tidur cukup)', 2),
('大好き', 'だいすき', 'daisuki', 'Sangat suka', '犬が大好き (Suka anjing)', 2),
('適当', 'てきとう', 'tekitou', 'Cocok/Pas', '適当な量 (Jumlah pas)', 2),
('特別', 'とくべつ', 'tokubetsu', 'Spesial', '特別な日 (Hari spesial)', 2),
('熱心', 'ねっしん', 'nesshin', 'Tekun', '熱心に働く (Kerja tekun)', 2),
('必要', 'ひつよう', 'hitsuyou', 'Perlu', 'お金が必要 (Butuh uang)', 2),
('不便', 'ふべん', 'fuben', 'Tidak praktis', '交通が不便 (Transport susah)', 2),
('無理', 'むり', 'muri', 'Mustahil', 'それは無理だ (Itu mustahil)', 2),
('有名', 'ゆうめい', 'yuumei', 'Terkenal', '有名な歌手 (Penyanyi top)', 2),
('立派', 'りっぱ', 'rippa', 'Megah', '立派な家 (Rumah megah)', 2),
('浅い', 'あさい', 'asai', 'Dangkal', '浅い川 (Sungai dangkal)', 2),
('厚い', 'あつい', 'atsui', 'Tebal', '厚い壁 (Dinding tebal)', 2),
('薄い', 'うすい', 'usui', 'Tipis', '薄い紙 (Kertas tipis)', 2),
('美しい', 'うつくしい', 'utsukushii', 'Indah', '美しい花 (Bunga indah)', 2),
('嬉しい', 'うれしい', 'ureshii', 'Senang', '会えて嬉しい (Senang bertemu)', 2),
('おかしい', 'おかしい', 'okashii', 'Aneh', '味が可笑しい (Rasa aneh)', 2),
('硬い', 'かたい', 'katai', 'Keras', '硬いパン (Roti keras)', 2),
('悲しい', 'かなしい', 'kanashii', 'Sedih', '悲しい話 (Cerita sedih)', 2),
('細かい', 'こまかい', 'komakai', 'Halus/Detail', '細かい字 (Tulisan kecil)', 2),
('寂しい', 'さびしい', 'sabishii', 'Kesepian', '一人で寂しい (Sepi sendiri)', 2),
('凄い', 'すごい', 'sugoi', 'Hebat', 'すごい技術 (Teknologi hebat)', 2),
('正しい', 'ただしい', 'tadashii', 'Benar', '正しい答え (Jawaban benar)', 2),
('苦い', 'にがい', 'nigai', 'Pahit', '苦い薬 (Obat pahit)', 2),
('眠い', 'ねむい', 'nemui', 'Mengantuk', '眠い目 (Mata ngantuk)', 2),
('恥ずかしい', 'はずかしい', 'hazukashii', 'Malu', '失敗して恥ずかしい (Malu gagal)', 2),
('酷い', 'ひどい', 'hidoi', 'Kejam/Parah', 'ひどい雨 (Hujan parah)', 2),
('深い', 'ふかい', 'fukai', 'Dalam', '深い海 (Laut dalam)', 2),
('珍しい', 'めずらしい', 'mezurashii', 'Langka', '珍しい切手 (Prangko langka)', 2),
('柔らかい', 'やわらかい', 'yawarakai', 'Lembut', '柔らかいパン (Roti lembut)', 2),
('優しい', 'やさしい', 'yasashii', 'Baik hati', '優しい人 (Orang baik)', 2),
('若', 'わかい', 'wakai', 'Muda', '若い人 (Anak muda)', 2),
('安心', 'あんしん', 'anshin', 'Lega', '安心する (Merasa lega)', 2),
('案内', 'あんない', 'annai', 'Panduan', '案内所 (Pusat info)', 2),
('以下', 'いか', 'ika', 'Kurang dari', '5人以下 (Dibawah 5 org)', 2),
('以上', 'いじょう', 'ijou', 'Lebih dari', '期待以上 (Lebih dr ekspektasi)', 2),
('以外', 'いがい', 'igai', 'Kecuali', 'これ以外 (Kecuali ini)', 2),
('医学', 'いがく', 'igaku', 'Kedokteran', '医学部 (Fakultas dokter)', 2),
('意見', 'いけん', 'iken', 'Pendapat', '意見を言う (Berpendapat)', 2),
('石', 'いし', 'ishi', 'Batu', '石を投げる (Lempar batu)', 2),
('田舎', 'いなか', 'inaka', 'Pedesaan', '田舎に帰る (Pulang kampung)', 2),
('嘘', 'うそ', 'uso', 'Bohong', '嘘をつく (Berbohong)', 2),
('運転', 'うんてん', 'unten', 'Menyetir', '車を運転 (Setir mobil)', 2),
('運動', 'うんどう', 'undou', 'Olahraga', '運動場 (Lapangan)', 2),
('枝', 'えだ', 'eda', 'Ranting', '木の枝 (Ranting pohon)', 2),
('遠慮', 'えんりょ', 'enryo', 'Sungkan', 'ご遠慮なく (Jangan sungkan)', 2),
('億', 'おく', 'oku', 'Ratus Juta', '1億円 (100 juta yen)', 2),
('屋上', 'おくじょう', 'okujou', 'Atap', 'ビルの屋上 (Atap gedung)', 2),
('お祝い', 'おいわい', 'oiwai', 'Perayaan', '結婚祝い (Hadiah nikah)', 2),
('お菓子', 'おかし', 'okashi', 'Camilan', 'お菓子を食べる (Makan jajan)', 2),
('お祭り', 'おまつり', 'omatsuri', 'Festival', '夏祭り (Festival musim panas)', 2),
('おもちゃ', 'おもちゃ', 'omocha', 'Mainan', 'おもちゃで遊ぶ (Main mainan)', 2),
('表', 'おもて', 'omote', 'Depan', '表と裏 (Depan belakang)', 2),
('海岸', 'かいがん', 'kaigan', 'Pantai', '海岸を歩く (Jalan di pantai)', 2),
('会議', 'かいぎ', 'kaigi', 'Rapat', '会議室 (Ruang rapat)', 2),
('会話', 'かいわ', 'kaiwa', 'Percakapan', '英会話 (Percakapan Inggris)', 2),
('鏡', 'かがみ', 'kagami', 'Cermin', '鏡を見る (Ngaca)', 2),
('壁', 'かべ', 'kabe', 'Dinding', '白い壁 (Dinding putih)', 2),
('看護師', 'かんごし', 'kangoshi', 'Perawat', '病院の看護師 (Perawat RS)', 2),
('関係', 'かんけい', 'kankei', 'Hubungan', '良い関係 (Hubungan baik)', 2),
('機会', 'きかい', 'kikai', 'Kesempatan', '良い機会 (Kesempatan bagus)', 2),
('規則', 'きそく', 'kisoku', 'Aturan', '交通規則 (Aturan lalin)', 2),
('絹', 'きぬ', 'kinu', 'Sutra', '絹の服 (Baju sutra)', 2),
('気分', 'きぶん', 'kibun', 'Mood', '気分が良い (Mood bagus)', 2),
('客', 'きゃく', 'kyaku', 'Tamu', 'お客様 (Tamu yth)', 2),
('急行', 'きゅうこう', 'kyuukou', 'Ekspres', '急行電車 (Kereta ekspres)', 2),
('教育', 'きょういく', 'kyouiku', 'Pendidikan', '学校教育 (Pendidikan sekolah)', 2),
('教会', 'きょうかい', 'kyoukai', 'Gereja', '教会で祈る (Berdoa di gereja)', 2),
('競争', 'きょうそう', 'kyousou', 'Kompetisi', '競争が激しい (Kompetisi ketat)', 2),
('興味', 'きょうみ', 'kyoumi', 'Minat', '日本に興味がある (Minat Jepang)', 2),
('近所', 'きんじょ', 'kinjo', 'Tetangga', '近所の人 (Orang sebelah)', 2),
('具合', 'ぐあい', 'guai', 'Kondisi', '具合が悪い (Sakit)', 2),
('空気', 'くうき', 'kuuki', 'Udara', 'きれいな空気 (Udara bersih)', 2),
('空港', 'くうこう', 'kuukou', 'Bandara', '空港へ行く (Ke bandara)', 2),
('草', 'くさ', 'kusa', 'Rumput', '草が生える (Rumput tumbuh)', 2),
('首', 'くび', 'kubi', 'Leher', '首が痛い (Sakit leher)', 2),
('雲', 'くも', 'kumo', 'Awan', '白い雲 (Awan putih)', 2),
('計画', 'けいかく', 'keikaku', 'Rencana', '計画を立てる (Buat rencana)', 2),
('警察', 'けいさつ', 'keisatsu', 'Polisi', '警察を呼ぶ (Panggil polisi)', 2),
('景色', 'けしき', 'keshiki', 'Pemandangan', '美しい景色 (Pemandangan indah)', 2),
('見物', 'けんぶつ', 'kenbutsu', 'Wisata', '東京見物 (Wisata Tokyo)', 2),
('郊外', 'こうがい', 'kougai', 'Pinggiran', '郊外に住む (Tinggal di pinggir kota)', 2),
('高校', 'こうこう', 'koukou', 'SMA', '高校に通う (Sekolah SMA)', 2),
('講義', 'こうぎ', 'kougi', 'Kuliah', '講義を聞く (Dengar kuliah)', 2),
('工業', 'こうぎょう', 'kougyou', 'Industri', '重工業 (Industri berat)', 2),
('工場', 'こうじょう', 'koujou', 'Pabrik', 'パン工場 (Pabrik roti)', 2),
('交通', 'こうつう', 'koutsuu', 'Lalu lintas', '交通安全 (Aman lalin)', 2),
('講堂', 'こうどう', 'koudou', 'Auditorium', '講堂に集まる (Kumpul di aula)', 2),
('国際', 'こくさい', 'kokusai', 'Internasional', '国際会議 (Konferensi intl)', 2),
('心', 'こころ', 'kokoro', 'Hati', '心が広い (Hati luas)', 2),
('故障', 'こしょう', 'koshou', 'Rusak', '車が故障する (Mobil rusak)', 2),
('ご存じ', 'ごぞんじ', 'gozonji', 'Tahu (Hormat)', 'ご存じですか (Anda tahu?)', 2),
('米', 'こめ', 'kome', 'Beras', '米を研ぐ (Cuci beras)', 2),
('今夜', 'こんや', 'konya', 'Malam ini', '今夜の予定 (Jadwal malam ini)', 2),
('最近', 'さいきん', 'saikin', 'Terkini', '最近の出来事 (Kejadian terkini)', 2),
('最後', 'さいご', 'saigo', 'Terakhir', '最後のチャンス (Kesempatan terakhir)', 2),
('最初', 'さいしょ', 'saisho', 'Pertama', '最初のページ (Halaman pertama)', 2),
('坂', 'さか', 'saka', 'Tanjakan', '坂を登る (Naik tanjakan)', 2),
('試合', 'しあい', 'shiai', 'Pertandingan', '試合に勝つ (Menang tanding)', 2),
('仕方', 'しかた', 'shikata', 'Cara', '仕方がない (Tak ada cara lain)', 2),
('試験', 'しけん', 'shiken', 'Ujian', '試験勉強 (Belajar ujian)', 2),
('事故', 'じこ', 'jiko', 'Kecelakaan', '事故に遭う (Kena kecelakaan)', 2),
('地震', 'じしん', 'jishin', 'Gempa', '地震が起きる (Gempa terjadi)', 2),
('時代', 'じだい', 'jidai', 'Zaman', '明治時代 (Zaman Meiji)', 2),
('失敗', 'しっぱい', 'shippai', 'Gagal', '失敗する (Gagal)', 2),
('邪魔', 'じゃま', 'jama', 'Gangguan', '邪魔をする (Mengganggu)', 2),
('自由', 'じゆう', 'jiyuu', 'Bebas', '自由席 (Kursi bebas)', 2),
('習慣', 'しゅうかん', 'shuukan', 'Kebiasaan', '生活習慣 (Kebiasaan hidup)', 2),
('住所', 'じゅうしょ', 'juusho', 'Alamat', '住所を書く (Tulis alamat)', 2),
('準備', 'じゅんび', 'junbi', 'Persiapan', '準備運動 (Pemanasan)', 2),
('招待', 'しょうたい', 'shoutai', 'Undangan', '招待状 (Kartu undangan)', 2),
('将来', 'しょうらい', 'shourai', 'Masa depan', '将来の夢 (Mimpi masa depan)', 2),
('食事', 'しょくじ', 'shokuji', 'Makan', '食事に行く (Pergi makan)', 2),
('食料品', 'しょくりょうひん', 'shokuryouhin', 'Bahan pangan', '食料品店 (Toko pangan)', 2),
('女性', 'じょせい', 'josei', 'Wanita', '女性専用 (Khusus wanita)', 2),
('神社', 'じんじゃ', 'jinja', 'Kuil', '神社へ行く (Ke kuil)', 2),
('人口', 'じんこう', 'jinkou', 'Populasi', '人口が増える (Populasi naik)', 2),
('水泳', 'すいえい', 'suiei', 'Renang', '水泳教室 (Kelas renang)', 2),
('水道', 'すいどう', 'suidou', 'Air keran', '水道水 (Air keran)', 2),
('数学', 'すうがく', 'suugaku', 'Matematika', '数学の問題 (Soal MTK)', 2),
('砂', 'すな', 'suna', 'Pasir', '砂浜 (Pantai pasir)', 2),
('政治', 'せいじ', 'seiji', 'Politik', '政治家 (Politisi)', 2),
('生活', 'せいかつ', 'seikatsu', 'Kehidupan', '楽しい生活 (Hidup senang)', 2),
('生産', 'せいさん', 'seisan', 'Produksi', '生産量 (Jumlah produksi)', 2),
('世界', 'せかい', 'sekai', 'Dunia', '世界一周 (Keliling dunia)', 2),
('席', 'せき', 'seki', 'Kursi', '席に着く (Duduk)', 2),
('説明', 'せつめい', 'setsumei', 'Penjelasan', '説明する (Menjelaskan)', 2),
('背中', 'せなか', 'senaka', 'Punggung', '背中が痛い (Sakit punggung)', 2),
('線', 'せん', 'sen', 'Garis', '線を引く (Tarik garis)', 2),
('戦争', 'せんそう', 'sensou', 'Perang', '戦争反対 (Anti perang)', 2),
('先輩', 'せんぱい', 'senpai', 'Senior', '会社の先輩 (Senior kantor)', 2),
('相談', 'そうだん', 'soudan', 'Konsultasi', '相談する (Berkonsultasi)', 2),
('卒業', 'そつぎょう', 'sotsugyou', 'Lulus', '大学卒業 (Lulus kuliah)', 2),
('祖父', 'そふ', 'sofu', 'Kakek', '祖父の家 (Rumah kakek)', 2),
('ソフト', 'そふと', 'sofuto', 'Lunak/Software', 'ソフトクリーム (Es krim cone)', 2),
('退院', 'たいいん', 'taiin', 'Keluar RS', '退院する (Keluar RS)', 2),
('大学', 'だいがく', 'daigaku', 'Universitas', '大学受験 (Ujian masuk univ)', 2),
('台風', 'たいふう', 'taifuu', 'Topan', '台風が来る (Topan datang)', 2),
('太陽', 'たいよう', 'taiyou', 'Matahari', '太陽が昇る (Matahari terbit)', 2),
('棚', 'たな', 'tana', 'Rak', '本棚 (Rak buku)', 2),
('誕生日', 'たんじょうび', 'tanjoubi', 'Ultah', '誕生日会 (Pesta ultah)', 2),
('暖房', 'だんぼう', 'danbou', 'Pemanas', '暖房をつける (Nyalakan pemanas)', 2),
('血', 'ち', 'chi', 'Darah', '血が出る (Berdarah)', 2),
('地下', 'ちか', 'chika', 'Bawah tanah', '地下鉄 (Subway)', 2),
('力', 'ちから', 'chikara', 'Kekuatan', '力持ち (Orang kuat)', 2),
('地図', 'ちず', 'chizu', 'Peta', '地図を見る (Lihat peta)', 2),
('茶色', 'ちゃいろ', 'chairo', 'Cokelat', '茶色の靴 (Sepatu cokelat)', 2),
('注意', 'ちゅうい', 'chuui', 'Hati-hati', '車に注意 (Awas mobil)', 2),
('中学校', 'ちゅうがっこう', 'chuugakkou', 'SMP', '中学校に通う (Sekolah SMP)', 2),
('注射', 'ちゅうしゃ', 'chuusha', 'Suntik', '注射を打つ (Disuntik)', 2),
('駐車場', 'ちゅうしゃじょう', 'chuushajou', 'Parkiran', '駐車場を探す (Cari parkir)', 2),
('地理', 'ちり', 'chiri', 'Geografi', '日本の地理 (Geografi Jepang)', 2),
('妻', 'つま', 'tsuma', 'Istri', '妻と出かける (Pergi dgn istri)', 2),
('都合', 'つごう', 'tsugou', 'Kondisi', '都合が悪い (Sibuk)', 2),
('手袋', 'てぶくろ', 'tebukuro', 'Sarung tangan', '手袋をする (Pakai sarung tangan)', 2),
('寺', 'てら', 'tera', 'Kuil', 'お寺 (Kuil)', 2),
('点', 'てん', 'ten', 'Poin', '100点 (Nilai 100)', 2),
('店員', 'てんいん', 'tenin', 'Pelayan', '店員さん (Mas/Mbak pelayan)', 2),
('天気予報', 'てんきよほう', 'tenkiyohou', 'Prakiraan', '天気予報を見る (Lihat cuaca)', 2),
('展覧会', 'てんらんかい', 'tenrankai', 'Pameran', '展覧会に行く (Ke pameran)', 2),
('都', 'と', 'to', 'Ibukota', '東京都 (Tokyo)', 2),
('道具', 'どうぐ', 'dougu', 'Alat', '掃除道具 (Alat bersih2)', 2),
('泥棒', 'どろぼう', 'dorobou', 'Pencuri', '泥棒が入る (Maling masuk)', 2),
('動物園', 'どうぶつえん', 'doubutsuen', 'Kebun binatang', '動物園へ行く (Ke bonbin)', 2),
('特急', 'とっきゅう', 'tokkyuu', 'Ekspres', '特急電車 (Kereta ekspres)', 2),
('途中', 'とちゅう', 'tochuu', 'Di jalan', '学校へ行く途中 (Di jalan ke sekolah)', 2),
('直る', 'なおる', 'naoru', 'Sembuh', '故障が直る (Rusak bener)', 2),
('亡くなる', 'なくなる', 'nakunaru', 'Meninggal', '祖母が亡くなる (Nenek wafat)', 2),
('入院', 'にゅういん', 'nyuuin', 'Opname', '入院する (Masuk RS)', 2),
('入学', 'にゅうがく', 'nyuugaku', 'Masuk sekolah', '入学式 (Upacara masuk)', 2),
('人形', 'にんぎょう', 'ningyou', 'Boneka', '人形遊び (Main boneka)', 2),
('値段', 'ねだん', 'nedan', 'Harga', '値段が高い (Mahal)', 2),
('熱', 'ねつ', 'netsu', 'Demam', '熱がある (Demam)', 2),
('乗り物', 'のりもの', 'norimono', 'Kendaraan', '乗り物酔い (Mabuk kendaraan)', 2),
('歯医者', 'はいしゃ', 'haisha', 'Dokter gigi', '歯医者に行く (Ke drg)', 2),
('場合', 'ばあい', 'baai', 'Situasi', '緊急の場合 (Situasi darurat)', 2),
('倍', 'ばい', 'bai', 'Kali lipat', '2倍 (2 kali lipat)', 2),
('拝見', 'はいけん', 'haiken', 'Melihat (Humble)', '拝見します (Saya lihat)', 2),
('箱', 'はこ', 'hako', 'Kotak', '箱に入れる (Masukan kotak)', 2),
('場所', 'ばしょ', 'basho', 'Tempat', '集合場所 (Tempat kumpul)', 2),
('発音', 'はつおん', 'hatsuon', 'Pelafalan', '発音がいい (Pelafalan bagus)', 2),
('林', 'はやし', 'hayashi', 'Hutan kecil', '林の中 (Di hutan)', 2),
('番組', 'ばんぐみ', 'bangumi', 'Acara TV', 'テレビ番組 (Acara TV)', 2),
('反対', 'はんたい', 'hantai', 'Lawan', '反対方向 (Arah lawan)', 2),
('火', 'ひ', 'hi', 'Api', '火事 (Kebakaran)', 2),
('冷える', 'ひえる', 'hieru', 'Dingin', '体が冷える (Badan dingin)', 2),
('引き出し', 'ひきだし', 'hikidashi', 'Laci', '机の引き出し (Laci meja)', 2),
('髭', 'ひげ', 'hige', 'Jenggot', '髭を剃る (Cukur jenggot)', 2),
('飛行場', 'ひこうじょう', 'hikoujou', 'Bandara', '飛行場へ行く (Ke bandara)', 2),
('美人', 'びじん', 'bijin', 'Wanita cantik', '彼女は美人 (Dia cantik)', 2),
('びっくり', 'びっくり', 'bikkuri', 'Kaget', 'びっくりした (Kaget!)', 2),
('昼間', 'ひるま', 'hiruma', 'Siang', '昼間は暑い (Siang panas)', 2),
('復習', 'ふくしゅう', 'fukushuu', 'Review', '復習する (Mengulang pelajaran)', 2),
('普通', 'ふつう', 'futsuu', 'Biasa', '普通電車 (Kereta biasa)', 2),
('葡萄', 'ぶどう', 'budou', 'Anggur', '葡萄狩り (Petik anggur)', 2),
('布団', 'ふとん', 'futon', 'Kasur', '布団を敷く (Gelar kasur)', 2),
('船', 'ふね', 'fune', 'Kapal', '船旅 (Perjalanan kapal)', 2),
('不便', 'ふべん', 'fuben', 'Repot', '交通が不便 (Transport susah)', 2),
('文化', 'ぶんか', 'bunka', 'Budaya', '日本文化 (Budaya Jepang)', 2),
('文学', 'ぶんがく', 'bungaku', 'Sastra', '日本文学 (Sastra Jepang)', 2),
('文法', 'ぶんぽう', 'bunpou', 'Tata bahasa', '文法を習う (Belajar grammar)', 2),
('平和', 'へいわ', 'heiwa', 'Damai', '平和な国 (Negara damai)', 2),
('変', 'へん', 'hen', 'Aneh', '変な音 (Suara aneh)', 2),
('貿易', 'ぼうえき', 'boueki', 'Perdagangan', '貿易会社 (Perusahaan dagang)', 2),
('放送', 'ほうそう', 'housou', 'Siaran', '放送局 (Stasiun TV/Radio)', 2),
('法律', 'ほうりつ', 'houritsu', 'Hukum', '法律を守る (Taat hukum)', 2),
('星', 'ほし', 'hoshi', 'Bintang', '星空 (Langit berbintang)', 2),
('翻訳', 'ほんやく', 'honyaku', 'Terjemahan', '翻訳家 (Penerjemah)', 2),
('湖', 'みずうみ', 'mizuumi', 'Danau', '琵琶湖 (Danau Biwa)', 2),
('港', 'みなと', 'minato', 'Pelabuhan', '港町 (Kota pelabuhan)', 2),
('虫', 'むし', 'mushi', 'Serangga', '虫刺され (Digigit serangga)', 2),
('息子', 'むすこ', 'musuko', 'Putra', '息子さん (Putra anda)', 2),
('娘', 'むすめ', 'musume', 'Putri', '娘さん (Putri anda)', 2),
('村', 'むら', 'mura', 'Desa', '村長 (Kepala desa)', 2),
('召し上がる', 'めしあがる', 'meshiagaru', 'Makan (Hormat)', '召し上がれ (Silakan makan)', 2),
('木綿', 'もめん', 'momen', 'Katun', '木綿の服 (Baju katun)', 2),
('森', 'もり', 'mori', 'Hutan', '森の動物 (Hewan hutan)', 2),
('約束', 'やくそく', 'yakusoku', 'Janji', '約束を破る (Ingkar janji)', 2),
('指', 'ゆび', 'yubi', 'Jari', '指輪 (Cincin)', 2),
('夢', 'ゆめ', 'yume', 'Mimpi', '夢を見る (Bermimpi)', 2),
('用事', 'ようじ', 'youji', 'Urusan', '急な用事 (Urusan mendadak)', 2),
('用意', 'ようい', 'youi', 'Persiapan', '用意周到 (Persiapan matang)', 2),
('予定', 'よてい', 'yotei', 'Rencana', '予定通り (Sesuai rencana)', 2),
('予約', 'よやく', 'yoyaku', 'Reservasi', '予約席 (Kursi pesanan)', 2),
('寄る', 'よる', 'yoru', 'Mampir', '店に寄る (Mampir toko)', 2),
('理由', 'りゆう', 'riyuu', 'Alasan', '理由を話す (Bicara alasan)', 2),
('利用', 'りよう', 'riyou', 'Guna', '再利用 (Daur ulang)', 2),
('両方', 'りょうほう', 'ryouhou', 'Keduanya', '両方欲しい (Mau keduanya)', 2),
('旅館', 'りょかん', 'ryokan', 'Ryokan', '旅館に泊まる (Nginap di Ryokan)', 2),
('留守', 'るす', 'rusu', 'Tidak ada', '留守番 (Jaga rumah)', 2),
('歴史', 'れきし', 'rekishi', 'Sejarah', '歴史の授業 (Pelajaran sejarah)', 2),
('連絡', 'れんらく', 'renraku', 'Kontak', '連絡先 (Kontak person)', 2),
('割合', 'わりあい', 'wariai', 'Rasio', '割合が高い (Rasio tinggi)', 2),
('割れる', 'われる', 'wareru', 'Pecah', 'コップが割れる (Gelas pecah)', 2),

-- KATA KETERANGAN & WAKTU N4 (ADVERBS/TIME)
('間', 'あいだ', 'aida', 'Antara/Selama', '夏休みの間 (Selama liburan musim panas)', 2),
('あっち', 'あっち', 'acchi', 'Di sana (Kasual)', 'あっちに行こう (Ayo pergi ke sana)', 2),
('後', 'あと', 'ato', 'Nanti/Sisa', '後で電話します (Nanti saya telepon)', 2),
('余り', 'あまり', 'amari', 'Tidak terlalu (negatif)', 'あまり好きじゃない (Tidak terlalu suka)', 2),
('或いは', 'あるいは', 'aruiwa', 'Atau/Mungkin', 'ペン、或いは鉛筆 (Pena, atau pensil)', 2),
('いかが', 'いかが', 'ikaga', 'Bagaimana (Sopan)', 'お元気はいかがですか (Bagaimana kabar anda?)', 2),
('幾ら', 'いくら', 'ikura', 'Berapa (Harga/Jumlah)', 'これは幾らですか (Ini harganya berapa?)', 2),
('幾つ', 'いくつ', 'ikutsu', 'Berapa (Benda/Umur)', 'おいくつですか (Umur berapa?)', 2),
('幾つ', 'いくら', 'ikura', 'Berapa banyak', 'みかんは幾つありますか (Ada berapa jeruk?)', 2),
('致す', 'いたす', 'itasu', 'Melakukan (Humble)', '私が致します (Saya yang akan melakukannya)', 2),
('一旦', 'いったん', 'ittan', 'Sekali/Sementara', '一旦家に帰る (Pulang ke rumah sebentar)', 2),
('一杯', 'いっぱい', 'ippai', 'Penuh', 'お腹がいっぱい (Perut penuh/kenyang)', 2),
('いつも', 'いつも', 'itsumo', 'Selalu', 'いつもありがとう (Terima kasih selalu)', 2),
('いよいよ', 'いよいよ', 'iyoiyo', 'Akhirnya/Semakin', 'いよいよ明日だ (Akhirnya besok)', 2),
('薄い', 'うすい', 'usui', 'Tipis/Tawar', '色が薄い (Warnanya tipis/pudar)', 2),
('美しい', 'うつくしい', 'utsukushii', 'Indah', '美しい海 (Laut yang indah)', 2),
('お祝い', 'おいわい', 'oiwai', 'Perayaan/Hadiah', '合格のお祝い (Hadiah kelulusan)', 2),
('おかげ', 'おかげ', 'okage', 'Berkat', 'あなたのおかげです (Berkat kamu)', 2),
('おかしい', 'おかしい', 'okashii', 'Aneh/Lucu', '頭がおかしい (Aneh/Gila)', 2),
('億', 'おく', 'oku', 'Ratus Juta', '1億円 (100 juta yen)', 2),
('屋上', 'おくじょう', 'okujou', 'Atap/Rooftop', '屋上でランチ (Makan siang di atap)', 2),
('遅く', 'おそく', 'osoku', 'Lambat/Larut', '夜遅く (Larut malam)', 2),
('お大事に', 'おだいじに', 'odaijini', 'Semoga lekas sembuh', 'どうぞお大事に (Semoga lekas sembuh ya)', 2),
('夫', 'おっと', 'otto', 'Suami (Sendiri)', '夫は会社員です (Suami saya karyawan)', 2),
('お釣り', 'おつり', 'otsuri', 'Kembalian', 'お釣りをもらう (Dapat kembalian)', 2),
('音', 'おと', 'oto', 'Suara/Bunyi', '雨の音 (Suara hujan)', 2),
('落とす', 'おとす', 'otosu', 'Menjatuhkan', 'スピードを落とす (Menurunkan kecepatan)', 2),
('踊り', 'おどり', 'odori', 'Tarian', '日本の踊り (Tarian Jepang)', 2),
('驚く', 'おどろく', 'odoroku', 'Terkejut', '結果に驚く (Terkejut dengan hasil)', 2),
('お祭り', 'おまつり', 'omatsuri', 'Festival', '村のお祭り (Festival desa)', 2),
('お見舞い', 'おみまい', 'omimai', 'Menjenguk', '病院へお見舞いに行く (Pergi menjenguk ke RS)', 2),
('お土産', 'おみやげ', 'omiyage', 'Oleh-oleh', '京都のお土産 (Oleh-oleh Kyoto)', 2),
('思い出す', 'おもいだす', 'omoidasu', 'Mengingat/Teringat', '名前を思い出す (Teringat namanya)', 2),
('思う', 'おもう', 'omou', 'Berpikir', '雨が降ると思う (Saya pikir akan hujan)', 2),
('おもちゃ', 'おもちゃ', 'omocha', 'Mainan', '新しいおもちゃ (Mainan baru)', 2),
('表', 'おもて', 'omote', 'Permukaan/Depan', '表と裏 (Depan dan belakang)', 2),
('親', 'おや', 'oya', 'Orang tua', '親孝行 (Berbakti pada ortu)', 2),
('泳ぎ方', 'およぎかた', 'oyogikata', 'Cara berenang', '泳ぎ方を習う (Belajar cara renang)', 2),
('終わる', 'おわる', 'owaru', 'Selesai', '夏が終わる (Musim panas berakhir)', 2),
('海岸', 'かいがん', 'kaigan', 'Pantai', '海岸を走る (Lari di pantai)', 2),
('会議', 'かいぎ', 'kaigi', 'Rapat', '会議室 (Ruang rapat)', 2),
('会議室', 'かいぎしつ', 'kaigishitsu', 'Ruang Rapat', '広い会議室 (Ruang rapat luas)', 2),
('会場', 'かいじょう', 'kaijou', 'Tempat acara', 'コンサート会場 (Tempat konser)', 2),
('会話', 'かいわ', 'kaiwa', 'Percakapan', '日本語の会話 (Percakapan Jepang)', 2),
('帰り', 'かえり', 'kaeri', 'Kepulangan', '帰りの時間 (Waktu pulang)', 2),
('変える', 'かえる', 'kaeru', 'Mengubah', '髪型を変える (Mengubah gaya rambut)', 2),
('科学', 'かがく', 'kagaku', 'Sains', '科学の進歩 (Kemajuan sains)', 2),
('鏡', 'かがみ', 'kagami', 'Cermin', '鏡を見る (Melihat cermin)', 2),
('掛ける', 'かける', 'kakeru', 'Menggantung/Memakai', '眼鏡を掛ける (Memakai kacamata)', 2),
('飾る', 'かざる', 'kazaru', 'Menghias', '部屋を飾る (Menghias kamar)', 2),
('火事', 'かじ', 'kaji', 'Kebakaran', '火事を消す (Memadamkan api)', 2),
('ガス', 'がす', 'gasu', 'Gas', 'ガスコンロ (Kompor gas)', 2),
('ガソリン', 'がそりん', 'gasorin', 'Bensin', 'ガソリンを入れる (Isi bensin)', 2),
('ガソリンスタンド', 'がそりんすたんど', 'gasorinsutando', 'Pom Bensin', 'ガソリンスタンドで働く (Kerja di pom)', 2),
('堅い', 'かたい', 'katai', 'Keras', '堅い約束 (Janji teguh)', 2),
('形', 'かたち', 'katachi', 'Bentuk', '変な形 (Bentuk aneh)', 2),
('片付ける', 'かたづける', 'katazukeru', 'Membereskan', '机を片付ける (Bereskan meja)', 2),
('課長', 'かちょう', 'kachou', 'Kepala Seksi', '田中課長 (Kepala seksi Tanaka)', 2),
('勝つ', 'かつ', 'katsu', 'Menang', 'ゲームに勝つ (Menang game)', 2),
('格好', 'かっこう', 'kakkou', 'Penampilan', '格好いい (Keren)', 2),
('家内', 'かない', 'kanai', 'Istri (Sendiri)', '私の家内 (Istri saya)', 2),
('悲しい', 'かなしい', 'kanashii', 'Sedih', '悲しい映画 (Film sedih)', 2),
('必ず', 'かならず', 'kanarazu', 'Pasti/Selalu', '必ず来てください (Pastikan datang)', 2),
('金持ち', 'かねもち', 'kanemochi', 'Orang kaya', '彼は金持ちだ (Dia kaya)', 2),
('彼女', 'かのじょ', 'kanojo', 'Pacar (Pr)/Dia', '彼女が出来た (Punya pacar)', 2),
('壁', 'かべ', 'kabe', 'Dinding', '壁に絵を掛ける (Gantung gambar di dinding)', 2),
('髪', 'かみ', 'kami', 'Rambut', '髪が長い (Rambut panjang)', 2),
('噛む', 'かむ', 'kamu', 'Menggigit', 'ガムを噛む (Mengunyah permen karet)', 2),
('通う', 'かよう', 'kayou', 'Pulang pergi', '学校に通う (Pergi sekolah rutin)', 2),
('彼', 'かれ', 'kare', 'Pacar (Lk)/Dia', '彼とデート (Kencan dengan pacar)', 2),
('彼ら', 'かれら', 'karera', 'Mereka', '彼らは学生です (Mereka mahasiswa)', 2),
('乾く', 'かわく', 'kawaku', 'Kering', '喉が渇く (Haus / Tenggorokan kering)', 2),
('代わり', 'かわり', 'kawari', 'Pengganti', '父の代わりに (Sebagai pengganti ayah)', 2),
('変わる', 'かわる', 'kawaru', 'Berubah', '天気が変わる (Cuaca berubah)', 2),
('考える', 'かんがえる', 'kangaeru', 'Berpikir', 'よく考える (Berpikir baik-baik)', 2),
('関係', 'かんけい', 'kankei', 'Hubungan', '関係ない (Tidak ada hubungan)', 2),
('看護師', 'かんごし', 'kangoshi', 'Perawat', '看護師になる (Jadi perawat)', 2),
('簡単', 'かんたん', 'kantan', 'Mudah', '簡単な問題 (Soal mudah)', 2),
('気', 'き', 'ki', 'Perasaan', '気が合う (Cocok)', 2),
('機会', 'きかい', 'kikai', 'Kesempatan', '機会があれば (Jika ada kesempatan)', 2),
('危険', 'きけん', 'kiken', 'Bahaya', '危険な場所 (Tempat bahaya)', 2),
('聞こえる', 'きこえる', 'kikoeru', 'Terdengar', '声が聞こえる (Suara terdengar)', 2),
('汽車', 'きしゃ', 'kisha', 'Kereta Uap', '汽車に乗る (Naik kereta uap)', 2),
('技術', 'ぎじゅつ', 'gijutsu', 'Teknologi', '高い技術 (Teknologi tinggi)', 2),
('季節', 'きせつ', 'kisetsu', 'Musim', '好きな季節 (Musim favorit)', 2),
('規則', 'きそく', 'kisoku', 'Peraturan', '規則を守る (Taat aturan)', 2),
('きっと', 'きっと', 'kitto', 'Pasti', 'きっと勝つ (Pasti menang)', 2),
('絹', 'きぬ', 'kinu', 'Sutra', '絹の着物 (Kimono sutra)', 2),
('厳しい', 'きびしい', 'kibishii', 'Tegas/Keras', '厳しい先生 (Guru tegas)', 2),
('気分', 'きぶん', 'kibun', 'Perasaan (Mood)', '気分が悪い (Tidak enak badan)', 2),
('決まる', 'きまる', 'kimaru', 'Diputuskan', '日程が決まる (Jadwal diputuskan)', 2),
('君', 'きみ', 'kimi', 'Kamu (Kasual)', '君の名前 (Namamu)', 2),
('決める', 'きめる', 'kimeru', 'Memutuskan', '自分で決める (Putuskan sendiri)', 2),
('気持ち', 'きもち', 'kimochi', 'Perasaan (Rasa)', '気持ちいい (Nyaman/Enak)', 2),
('着物', 'きもの', 'kimono', 'Kimono', '着物を着る (Pakai kimono)', 2),
('客', 'きゃく', 'kyaku', 'Tamu/Pelanggan', '客が来る (Tamu datang)', 2),
('急', 'きゅう', 'kyuu', 'Tiba-tiba/Darurat', '急な用事 (Urusan mendadak)', 2),
('急行', 'きゅうこう', 'kyuukou', 'Kereta Ekspres', '急行に乗る (Naik ekspres)', 2),
('教育', 'きょういく', 'kyouiku', 'Pendidikan', '教育を受ける (Terima pendidikan)', 2),
('教会', 'きょうかい', 'kyoukai', 'Gereja', '教会へ行く (Pergi ke gereja)', 2),
('競争', 'きょうそう', 'kyousou', 'Kompetisi', '競争する (Berkompetisi)', 2),
('興味', 'きょうみ', 'kyoumi', 'Minat', '興味がある (Ada minat)', 2),
('近所', 'きんじょ', 'kinjo', 'Lingkungan/Tetangga', '近所の人 (Tetangga)', 2),
('具合', 'ぐあい', 'guai', 'Kondisi', '具合はどう? (Gimana kondisinya?)', 2),
('空気', 'くうき', 'kuuki', 'Udara', '空気がきれい (Udara bersih)', 2),
('空港', 'くうこう', 'kuukou', 'Bandara', '空港に着く (Tiba di bandara)', 2),
('草', 'くさ', 'kusa', 'Rumput', '草の上に座る (Duduk di rumput)', 2),
('くださる', 'くださる', 'kudasaru', 'Memberi (Hormat)', '先生がくださった (Guru memberikan)', 2),
('首', 'くび', 'kubi', 'Leher', '首が痛い (Leher sakit)', 2),
('雲', 'くも', 'kumo', 'Awan', '雲が多い (Banyak awan)', 2),
('比べる', 'くらべる', 'kuraberu', 'Membandingkan', '値段を比べる (Bandingkan harga)', 2),
('暮れる', 'くれる', 'kureru', 'Menjadi gelap', '日が暮れる (Matahari terbenam)', 2),
('君', 'くん', 'kun', 'Panggilan (Lk)', '田中君 (Tanaka-kun)', 2),
('毛', 'け', 'ke', 'Bulu/Rambut', '猫の毛 (Bulu kucing)', 2),
('計画', 'けいかく', 'keikaku', 'Rencana', '計画を立てる (Buat rencana)', 2),
('経験', 'けいけん', 'keiken', 'Pengalaman', '経験がある (Punya pengalaman)', 2),
('経済', 'けいざい', 'keizai', 'Ekonomi', '経済学部 (Fakultas ekonomi)', 2),
('警察', 'けいさつ', 'keisatsu', 'Polisi', '警察官 (Petugas polisi)', 2),
('怪我', 'けが', 'kega', 'Luka/Cedera', '怪我をした (Terluka)', 2),
('景色', 'けしき', 'keshiki', 'Pemandangan', '景色が良い (Pemandangan bagus)', 2),
('消しゴム', 'けしごむ', 'keshigomu', 'Penghapus', '消しゴムで消す (Hapus pakai penghapus)', 2),
('下宿', 'げしゅく', 'geshuku', 'Kos/Lodging', '下宿を探す (Cari kosan)', 2),
('決して', 'けっして', 'kesshite', 'Sama sekali tidak', '決して忘れない (Takkan pernah lupa)', 2),
('けれど', 'けれど', 'keredo', 'Tetapi', '好きだけれど (Suka sih, tapi...)', 2),
('原因', 'げんいん', 'genin', 'Penyebab', '事故の原因 (Penyebab kecelakaan)', 2),
('喧嘩', 'けんか', 'kenka', 'Pertengkaran', '喧嘩をやめる (Stop bertengkar)', 2),
('研究', 'けんきゅう', 'kenkyuu', 'Penelitian', '日本語の研究 (Penelitian bhs Jepang)', 2),
('研究室', 'けんきゅうしつ', 'kenkyuushitsu', 'Ruang Lab/Riset', '教授の研究室 (Ruang riset profesor)', 2),
('見物', 'けんぶつ', 'kenbutsu', 'Wisata/Sightseeing', 'お城を見物する (Wisata kastil)', 2),
('子', 'こ', 'ko', 'Anak', 'いい子 (Anak baik)', 2),
('こう', 'こう', 'kou', 'Seperti ini', 'こうやる (Lakukan seperti ini)', 2),
('郊外', 'こうがい', 'kougai', 'Pinggiran kota', '郊外の家 (Rumah pinggiran)', 2),
('講義', 'こうぎ', 'kougi', 'Kuliah', '講義が始まる (Kuliah mulai)', 2),
('工業', 'こうぎょう', 'kougyou', 'Industri', '工業地帯 (Kawasan industri)', 2),
('高校', 'こうこう', 'koukou', 'SMA', '高校生 (Siswa SMA)', 2),
('校長', 'こうちょう', 'kouchou', 'Kepala Sekolah', '校長先生 (Bapak Kepsek)', 2),
('交通', 'こうつう', 'koutsuu', 'Lalu Lintas', '交通安全 (Keselamatan lalin)', 2),
('講堂', 'こうどう', 'koudou', 'Auditorium', '講堂に集まる (Kumpul di auditorium)', 2),
('高等学校', 'こうとうがっこう', 'koutougakkou', 'SMA (Formal)', '高等学校卒業 (Lulusan SMA)', 2),
('公務員', 'こうむいん', 'koumuin', 'PNS', '公務員試験 (Ujian PNS)', 2),
('国際', 'こくさい', 'kokusai', 'Internasional', '国際的な (Internasional)', 2),
('心', 'こころ', 'kokoro', 'Hati', '心が痛い (Hati sakit)', 2),
('故障', 'こしょう', 'koshou', 'Kerusakan (Mesin)', '故障中 (Sedang rusak)', 2),
('ご存じ', 'ごぞんじ', 'gozonji', 'Mengetahui (Hormat)', 'ご存じですか (Anda tahu?)', 2),
('答', 'こたえ', 'kotae', 'Jawaban', '答えを書く (Tulis jawaban)', 2),
('ご馳走', 'ごちそう', 'gochisou', 'Jamuan makan', 'ご馳走さまでした (Terimakasih makanannya)', 2),
('こと', 'こと', 'koto', 'Hal', '大切なこと (Hal penting)', 2),
('小鳥', 'ことり', 'kotori', 'Burung kecil', '小鳥が飛ぶ (Burung terbang)', 2),
('この間', 'このあいだ', 'konoaida', 'Baru-baru ini', 'この間会った (Baru-baru ini ketemu)', 2),
('この頃', 'このごろ', 'konogoro', 'Akhir-akhir ini', 'この頃忙しい (Akhir-akhir ini sibuk)', 2),
('細かい', 'こまかい', 'komakai', 'Halus/Kecil', '細かいお金 (Uang receh)', 2),
('ゴミ', 'ごみ', 'gomi', 'Sampah', 'ゴミを出す (Buang sampah)', 2),
('込む', 'こむ', 'komu', 'Penuh/Macet', '店が込む (Toko penuh)', 2),
('米', 'こめ', 'kome', 'Beras', '米を買う (Beli beras)', 2),
('これら', 'これら', 'korera', 'Ini (Jamak)', 'これらは本です (Ini semua buku)', 2),
('怖い', 'こわい', 'kowai', 'Takut', 'お化けが怖い (Takut hantu)', 2),
('壊す', 'こわす', 'kowasu', 'Merusak', 'おもちゃを壊す (Merusak mainan)', 2),
('壊れる', 'こわれる', 'kowareru', 'Rusak', '椅子が壊れる (Kursi rusak)', 2),
('今度', 'こんど', 'kondo', 'Kali ini/Nanti', '今度遊びに来て (Nanti main ya)', 2),
('今夜', 'こんや', 'konya', 'Malam ini', '今夜の予定 (Jadwal malam ini)', 2),
('最近', 'さいきん', 'saikin', 'Terkini', '最近どう？ (Gimana kabarmu?)', 2),
('最後', 'さいご', 'saigo', 'Terakhir', '最後の質問 (Pertanyaan terakhir)', 2),
('最初', 'さいしょ', 'saisho', 'Pertama', '最初から (Dari awal)', 2),
('坂', 'さか', 'saka', 'Tanjakan', '坂を下りる (Turun tanjakan)', 2),
('探す', 'さがす', 'sagasu', 'Mencari', '仕事を探す (Cari kerja)', 2),
('下がる', 'さがる', 'sagaru', 'Turun', '熱が下がる (Demam turun)', 2),
('盛ん', 'さかん', 'sakan', 'Populer/Makmur', 'スポーツが盛ん (Olahraga populer)', 2),
('下げる', 'さげる', 'sageru', 'Menurunkan', '音量を下げる (Kecilkan volume)', 2),
('差し上げる', 'さしあげる', 'sashiageru', 'Memberikan (Humble)', 'お花を差し上げる (Memberi bunga)', 2),
('さっき', 'さっき', 'sakki', 'Tadi', 'さっき食べた (Tadi sudah makan)', 2),
('寂しい', 'さびしい', 'sabishii', 'Kesepian', '寂しい夜 (Malam sepi)', 2),
('さ来月', 'さらいげつ', 'saraigetsu', 'Dua bulan lagi', 'さ来月の予定 (Jadwal 2 bulan lagi)', 2),
('さ来週', 'さらいしゅう', 'saraishuu', 'Dua minggu lagi', 'さ来週会う (Ketemu 2 minggu lagi)', 2),
('サラダ', 'さらだ', 'sarada', 'Salad', '野菜サラダ (Salad sayur)', 2),
('騒ぐ', 'さわぐ', 'sawagu', 'Ribut', '大声で騒ぐ (Ribut suara keras)', 2),
('触る', 'さわる', 'sawaru', 'Menyentuh', '触らないで (Jangan sentuh)', 2),
('産業', 'さんぎょう', 'sangyou', 'Industri', '自動車産業 (Industri mobil)', 2),
('サンダル', 'さんだる', 'sandaru', 'Sandal', 'サンダルを履く (Pakai sandal)', 2),
('サンドイッチ', 'さんどいっち', 'sandoicchi', 'Sandwich', 'サンドイッチを作る (Buat sandwich)', 2),
('残念', 'ざんねん', 'zannen', 'Sayang sekali', '残念な結果 (Hasil mengecewakan)', 2),
('市', 'し', 'shi', 'Kota', '横浜市 (Kota Yokohama)', 2),
('字', 'じ', 'ji', 'Huruf', 'きれいな字 (Tulisan bagus)', 2),
('試合', 'しあい', 'shiai', 'Pertandingan', '試合に負ける (Kalah tanding)', 2),
('仕方', 'しかた', 'shikata', 'Cara', '勉強の仕方 (Cara belajar)', 2),
('叱る', 'しかる', 'shikaru', 'Memarahi', '母に叱られる (Dimarahi ibu)', 2),
('試験', 'しけん', 'shiken', 'Ujian', '試験を受ける (Ikut ujian)', 2),
('事故', 'じこ', 'jiko', 'Kecelakaan', '事故にあう (Kena kecelakaan)', 2),
('地震', 'じしん', 'jishin', 'Gempa', '地震が怖い (Takut gempa)', 2),
('時代', 'じだい', 'jidai', 'Zaman', '子供の時代 (Zaman anak-anak)', 2),
('下着', 'したぎ', 'shitagi', 'Pakaian dalam', '下着を買う (Beli pakaian dalam)', 2),
('支度', 'したく', 'shitaku', 'Persiapan', '出かける支度 (Siap-siap pergi)', 2),
('しっかり', 'しっかり', 'shikkari', 'Kuat/Tegas', 'しっかり勉強する (Belajar sungguh2)', 2),
('失敗', 'しっぱい', 'shippai', 'Gagal', '計画の失敗 (Gagal rencana)', 2),
('失礼', 'しつれい', 'shitsurei', 'Tidak sopan', '失礼な人 (Orang tidak sopan)', 2),
('辞典', 'じてん', 'jiten', 'Kamus', '電子辞典 (Kamus elektronik)', 2),
('品物', 'しなもの', 'shinamono', 'Barang', '品物が届く (Barang sampai)', 2),
('しばらく', 'しばらく', 'shibaraku', 'Sebentar', 'しばらく待つ (Tunggu sebentar)', 2),
('島', 'しま', 'shima', 'Pulau', '小さな島 (Pulau kecil)', 2),
('市民', 'しみん', 'shimin', 'Warga', '市民会館 (Gedung warga)', 2),
('閉める', 'しめる', 'shimeru', 'Menutup', 'カーテンを閉める (Tutup gorden)', 2),
('社会', 'しゃかい', 'shakai', 'Masyarakat', '社会問題 (Masalah sosial)', 2),
('社長', 'しゃちょう', 'shachou', 'Presdir', '社長に会う (Bertemu presdir)', 2),
('邪魔', 'じゃま', 'jama', 'Gangguan', 'お邪魔します (Permisi masuk)', 2),
('ジャム', 'じゃむ', 'jamu', 'Selai', 'イチゴジャム (Selai stroberi)', 2),
('自由', 'じゆう', 'jiyuu', 'Bebas', '自由な時間 (Waktu bebas)', 2),
('習慣', 'しゅうかん', 'shuukan', 'Kebiasaan', '日本の習慣 (Kebiasaan Jepang)', 2),
('住所', 'じゅうしょ', 'juusho', 'Alamat', '住所変更 (Ganti alamat)', 2),
('柔道', 'じゅうどう', 'juudou', 'Judo', '柔道の練習 (Latihan judo)', 2),
('十分', 'じゅうぶん', 'juubun', 'Cukup', '十分なお金 (Uang cukup)', 2),
('出席', 'しゅっせき', 'shusseki', 'Hadir', '会議に出席 (Hadir rapat)', 2),
('出発', 'しゅっぱつ', 'shuppatsu', 'Berangkat', 'バスが出発する (Bus berangkat)', 2),
('趣味', 'しゅみ', 'shumi', 'Hobi', '趣味は読書 (Hobi baca buku)', 2),
('準備', 'じゅんび', 'junbi', 'Persiapan', '心の準備 (Persiapan hati)', 2),
('紹介', 'しょうかい', 'shoukai', 'Perkenalan', '友達を紹介する (Kenalkan teman)', 2),
('小学校', 'しょうがっこう', 'shougakkou', 'SD', '小学校に入る (Masuk SD)', 2),
('小説', 'しょうせつ', 'shousetsu', 'Novel', '小説を読む (Baca novel)', 2),
('招待', 'しょうたい', 'shoutai', 'Undangan', '招待を受ける (Dapat undangan)', 2),
('承知', 'しょうち', 'shouchi', 'Mengerti (Hormat)', '承知いたしました (Baik, saya mengerti)', 2),
('将来', 'しょうらい', 'shourai', 'Masa depan', '将来の夢 (Mimpi masa depan)', 2),
('食事', 'しょくじ', 'shokuji', 'Makan', '食事の時間 (Waktu makan)', 2),
('食料品', 'しょくりょうひん', 'shokuryouhin', 'Bahan makanan', '食料品売り場 (Bagian makanan)', 2),
('女性', 'じょせい', 'josei', 'Wanita', '女性トイレ (Toilet wanita)', 2),
('知らせる', 'しらせる', 'shiraseru', 'Memberitahu', 'みんなに知らせる (Beritahu semua)', 2),
('調べる', 'しらべる', 'shiraberu', 'Memeriksa', '時刻表を調べる (Cek jadwal)', 2),
('人口', 'じんこう', 'jinkou', 'Populasi', '人口密度 (Kepadatan penduduk)', 2),
('神社', 'じんじゃ', 'jinja', 'Kuil', '神社で祈る (Berdoa di kuil)', 2),
('親切', 'しんせつ', 'shinsetsu', 'Ramah', '親切な人 (Orang ramah)', 2),
('心配', 'しんぱい', 'shinpai', 'Khawatir', '心配しないで (Jangan khawatir)', 2),
('新聞社', 'しんぶんしゃ', 'shinbunsha', 'Perusahaan Koran', '新聞社を見学 (Kunjungan ke koran)', 2),
('水泳', 'すいえい', 'suiei', 'Renang', '水泳選手 (Atlet renang)', 2),
('水道', 'すいどう', 'suidou', 'Ledeng', '水道水 (Air keran)', 2),
('ずいぶん', 'ずいぶん', 'zuibun', 'Sangat/Cukup', 'ずいぶん待った (Menunggu cukup lama)', 2),
('数学', 'すうがく', 'suugaku', 'Matematika', '数学の先生 (Guru MTK)', 2),
('スーツ', 'すーつ', 'suutsu', 'Jas/Suit', 'スーツを着る (Pakai jas)', 2),
('スーツケース', 'すーつけーす', 'suutsukeesu', 'Koper', '重いスーツケース (Koper berat)', 2),
('過ぎる', 'すぎる', 'sugiru', 'Melewati', '冬が過ぎる (Musim dingin berlalu)', 2),
('すく', 'すく', 'suku', 'Sepi/Kosong', '電車がすく (Kereta sepi)', 2),
('スクリーン', 'すくりーん', 'sukuriin', 'Layar', '大きなスクリーン (Layar besar)', 2),
('凄い', 'すごい', 'sugoi', 'Hebat', 'すごい雨 (Hujan hebat)', 2),
('進む', 'すすむ', 'susumu', 'Maju', '前に進む (Maju ke depan)', 2),
('すっかり', 'すっかり', 'sukkari', 'Sepenuhnya', 'すっかり忘れた (Lupa sama sekali)', 2),
('ずっと', 'ずっと', 'zutto', 'Terus/Jauh lebih', 'ずっと前 (Jauh sebelumnya)', 2),
('ステーキ', 'すてーき', 'suteeki', 'Steak', 'ステーキを焼く (Bakar steak)', 2),
('捨てる', 'すてる', 'suteru', 'Membuang', 'ゴミを捨てる (Buang sampah)', 2),
('ステレオ', 'すてれお', 'sutereo', 'Stereo', 'ステレオで聞く (Dengar stereo)', 2),
('砂', 'すな', 'suna', 'Pasir', '砂の城 (Istana pasir)', 2),
('すばらしい', 'すばらしい', 'subarashii', 'Luar biasa', '素晴らしい考え (Ide bagus)', 2),
('滑る', 'すべる', 'suberu', 'Terpeleset', '足が滑る (Kaki terpeleset)', 2),
('隅', 'すみ', 'sumi', 'Pojok', '部屋の隅 (Pojok kamar)', 2),
('済む', 'すむ', 'sumu', 'Selesai', '仕事が済む (Kerjaan beres)', 2),
('すり', 'すり', 'suri', 'Copet', 'すりにあう (Kecopetan)', 2),
('すると', 'すると', 'suruto', 'Lalu/Kemudian', 'すると雨が降った (Lalu hujan turun)', 2),
('生活', 'せいかつ', 'seikatsu', 'Kehidupan', '大学生活 (Kehidupan kampus)', 2),
('生産', 'せいさん', 'seisan', 'Produksi', '生産中止 (Stop produksi)', 2),
('政治', 'せいじ', 'seiji', 'Politik', '政治に興味がある (Minat politik)', 2),
('西洋', 'せいよう', 'seiyou', 'Barat (Western)', '西洋文化 (Budaya barat)', 2),
('世界', 'せかい', 'sekai', 'Dunia', '世界平和 (Perdamaian dunia)', 2),
('席', 'せき', 'seki', 'Kursi', '席を立つ (Berdiri dari kursi)', 2),
('説明', 'せつめい', 'setsumei', 'Penjelasan', '説明が上手 (Pintar menjelaskan)', 2),
('背中', 'せなか', 'senaka', 'Punggung', '背中をかく (Garuk punggung)', 2),
('ぜひ', 'ぜひ', 'zehi', 'Pasti/Tentu', 'ぜひ来てください (Datanglah)', 2),
('世話', 'せわ', 'sewa', 'Merawat', '犬の世話 (Merawat anjing)', 2),
('線', 'せん', 'sen', 'Garis', '赤い線 (Garis merah)', 2),
('ぜんぜん', 'ぜんぜん', 'zenzen', 'Sama sekali tidak', '全然わからない (Tidak tahu sama sekali)', 2),
('戦争', 'せんそう', 'sensou', 'Perang', '戦争が起きる (Perang terjadi)', 2),
('先輩', 'せんぱい', 'senpai', 'Senior', '優しい先輩 (Senior baik)', 2),
('そう', 'そう', 'sou', 'Begitu', 'そうですか (Oh begitu)', 2),
('相談', 'そうだん', 'soudan', 'Konsultasi', '親に相談する (Konsul ke ortu)', 2),
('育てる', 'そだてる', 'sodateru', 'Membesarkan', '子供を育てる (Besarkan anak)', 2),
('卒業', 'そつぎょう', 'sotsugyou', 'Lulus', '卒業アルバム (Album kelulusan)', 2),
('祖父', 'そふ', 'sofu', 'Kakek (Sendiri)', '私の祖父 (Kakek saya)', 2),
('ソフト', 'そふと', 'sofuto', 'Lunak/Software', '柔らかいソフト (Lembut)', 2),
('祖母', 'そぼ', 'sobo', 'Nenek (Sendiri)', '私の祖母 (Nenek saya)', 2),
('それで', 'それで', 'sorede', 'Lalu/Jadi', 'それでどうした？ (Lalu gimana?)', 2),
('それに', 'それに', 'soreni', 'Selain itu', 'それに安い (Selain itu murah)', 2),
('それほど', 'それほど', 'sorehodo', 'Tidak seberapa', 'それほどでもない (Gak segitunya)', 2),
('そろそろ', 'そろそろ', 'sorosoro', 'Sebentar lagi', 'そろそろ行こう (Ayo berangkat)', 2),
('そんな', 'そんな', 'sonna', 'Seperti itu', 'そんなことない (Gak gitu kok)', 2),
('そんなに', 'そんなに', 'sonnani', 'Sebegitunya', 'そんなに高くない (Gak semahal itu)', 2),
('退院', 'たいいん', 'taiin', 'Keluar RS', '退院の手続き (Prosedur keluar RS)', 2),
('大学', 'だいがく', 'daigaku', 'Universitas', '大学へ行く (Pergi ke univ)', 2),
('大学生', 'だいがくせい', 'daigakusei', 'Mahasiswa', '私は大学生 (Saya mahasiswa)', 2),
('大事', 'だいじ', 'daiji', 'Penting', '大事な話 (Cerita penting)', 2),
('大体', 'だいたい', 'daitai', 'Kira-kira', '大体わかった (Kira-kira paham)', 2),
('たいてい', 'たいてい', 'taitei', 'Biasanya', 'たいてい家にいる (Biasanya di rumah)', 2),
('タイプ', 'たいぷ', 'taipu', 'Tipe', '好きなタイプ (Tipe idaman)', 2),
('台風', 'たいふう', 'taifuu', 'Topan', '台風が来る (Topan datang)', 2),
('倒れる', 'たおれる', 'taoreru', 'Roboh', '木が倒れる (Pohon roboh)', 2),
('だから', 'だから', 'dakara', 'Oleh karena itu', 'だから言ったのに (Kan udah kubilang)', 2),
('確か', 'たしか', 'tashika', 'Sepertinya', '確かそうです (Sepertinya begitu)', 2),
('足す', 'たす', 'tasu', 'Menambah', '足して2で割る (Tambah lalu bagi 2)', 2),
('訪ねる', 'たずねる', 'tazuneru', 'Berkunjung', '京都を訪ねる (Kunjung ke Kyoto)', 2),
('尋ねる', 'たずねる', 'tazuneru', 'Bertanya', '道を尋ねる (Tanya jalan)', 2),
('正しい', 'ただしい', 'tadashii', 'Benar', '正しい答え (Jawaban benar)', 2),
('畳', 'たたみ', 'tatami', 'Tatami', '畳の匂い (Bau tatami)', 2),
('立てる', 'たてる', 'tateru', 'Mendirikan', '旗を立てる (Dirikan bendera)', 2),
('建てる', 'たてる', 'tateru', 'Membangun', '家を建てる (Bangun rumah)', 2),
('例えば', 'たとえば', 'tatoeba', 'Contohnya', '例えばこれ (Contohnya ini)', 2),
('棚', 'たな', 'tana', 'Rak', '本棚 (Rak buku)', 2),
('楽しみ', 'たのしみ', 'tanoshimi', 'Kesenangan', '楽しみです (Saya menantikannya)', 2),
('楽む', 'たのしむ', 'tanoshimu', 'Menikmati', '音楽を楽しむ (Nikmati musik)', 2),
('たまに', 'たまに', 'tamani', 'Kadang-kadang', 'たまに会う (Kadang ketemu)', 2),
('為', 'ため', 'tame', 'Demi', '健康の為 (Demi kesehatan)', 2),
('だめ', 'だめ', 'dame', 'Jangan/Tidak boleh', 'それはだめ (Itu tidak boleh)', 2),
('足りる', 'たりる', 'tariru', 'Cukup', '時間が足りる (Waktu cukup)', 2),
('男性', 'だんせい', 'dansei', 'Pria', '男性用 (Untuk pria)', 2),
('暖房', 'だんぼう', 'danbou', 'Pemanas', '暖房が効く (Pemanasnya ampuh)', 2),
('血', 'ち', 'chi', 'Darah', '血が出る (Keluar darah)', 2),
('チェック', 'ちぇっく', 'chekku', 'Periksa', '要チェック (Perlu diperiksa)', 2),
('力', 'ちから', 'chikara', 'Tenaga', '力仕事 (Kerja fisik)', 2),
('ちっとも', 'ちっとも', 'chittomo', 'Sama sekali tidak', 'ちっとも知らない (Gak tau sama sekali)', 2),
('ちゃん', 'ちゃん', 'chan', 'Panggilan (Anak)', '猫ちゃん (Kucing-chan)', 2),
('注意', 'ちゅうい', 'chuui', 'Perhatian', '注意書き (Peringatan)', 2),
('中学校', 'ちゅうがっこう', 'chuugakkou', 'SMP', '中学校に通う (Sekolah di SMP)', 2),
('注射', 'ちゅうしゃ', 'chuusha', 'Suntik', '注射が怖い (Takut suntik)', 2),
('駐車場', 'ちゅうしゃじょう', 'chuushajou', 'Parkiran', '駐車場が満車 (Parkiran penuh)', 2),
('地理', 'ちり', 'chiri', 'Geografi', '地理の勉強 (Belajar geo)', 2),
('捕まえる', 'つかまえる', 'tsukamaeru', 'Menangkap', '虫を捕まえる (Tangkap serangga)', 2),
('付く', 'つく', 'tsuku', 'Menempel', 'しみが付く (Noda nempel)', 2),
('漬ける', 'つける', 'tsukeru', 'Merendam', '漬物をつける (Buat asinan)', 2),
('都合', 'つごう', 'tsugou', 'Keadaan', '都合がいい (Waktunya pas)', 2),
('伝える', 'つたえる', 'tsutaeru', 'Menyampaikan', 'よろしく伝えて (Sampaikan salam)', 2),
('続く', 'つづく', 'tsuzuku', 'Berlanjut', '道が続く (Jalan berlanjut)', 2),
('続ける', 'つづける', 'tsuzukeru', 'Melanjutkan', '話を続ける (Lanjut cerita)', 2),
('包む', 'つつむ', 'tsutsumu', 'Membungkus', 'プレゼントを包む (Bungkus kado)', 2),
('妻', 'つま', 'tsuma', 'Istri', '妻と娘 (Istri dan anak)', 2),
('つもり', 'つもり', 'tsumori', 'Niat', '行くつもり (Berniat pergi)', 2),
('釣る', 'つる', 'tsuru', 'Memancing', '魚を釣る (Mancing ikan)', 2),
('連れる', 'つれる', 'tsureru', 'Mengajak', '犬を連れる (Ajak anjing)', 2),
('丁寧', 'ていねい', 'teinei', 'Sopan', '丁寧な人 (Orang sopan)', 2),
('テキスト', 'てきすと', 'tekisuto', 'Buku teks', '日本語のテキスト (Buku teks Jepang)', 2),
('適当', 'てきとう', 'tekitou', 'Tepat/Asal', '適当に選ぶ (Pilih asal/tepat)', 2),
('できるだけ', 'できるだけ', 'dekirudake', 'Sebisa mungkin', 'できるだけ早く (Sebisa mungkin cepat)', 2),
('手伝う', 'てつだう', 'tetsudau', 'Membantu', '父を手伝う (Bantu ayah)', 2),
('テニス', 'てにす', 'tenisu', 'Tenis', 'テニスをする (Main tenis)', 2),
('手袋', 'てぶくろ', 'tebukuro', 'Sarung tangan', '手袋をはめる (Pakai sarung tangan)', 2),
('寺', 'てら', 'tera', 'Kuil', '寺の鐘 (Lonceng kuil)', 2),
('点', 'てん', 'ten', 'Nilai/Titik', '良い点を取る (Dapat nilai bagus)', 2),
('店員', 'てんいん', 'tenin', 'Pelayan', '店員さん (Mas pelayan)', 2),
('天気予報', 'てんきよほう', 'tenkiyohou', 'Ramalan Cuaca', '天気予報を見る (Lihat cuaca)', 2),
('展覧会', 'てんらんかい', 'tenrankai', 'Pameran', '展覧会に行く (Pergi pameran)', 2),
('都', 'と', 'to', 'Metropolis', '東京都 (Tokyo)', 2),
('道具', 'どうぐ', 'dougu', 'Alat', '便利な道具 (Alat praktis)', 2),
('とうとう', 'とうとう', 'toutou', 'Akhirnya', 'とうとう終わった (Akhirnya selesai)', 2),
('動物園', 'どうぶつえん', 'doubutsuen', 'Kebun Binatang', '動物園へ行く (Ke bonbin)', 2),
('遠く', 'とおく', 'tooku', 'Jauh', '遠くへ行きたい (Ingin pergi jauh)', 2),
('通る', 'とおる', 'tooru', 'Melewati', '家の前を通る (Lewat depan rumah)', 2),
('特に', 'とくに', 'tokuni', 'Khususnya', '特に好き (Sangat suka)', 2),
('特別', 'とくべつ', 'tokubetsu', 'Spesial', '特別な日 (Hari spesial)', 2),
('解く', 'とく', 'toku', 'Memecahkan', '問題を解く (Pecahkan soal)', 2),
('特急', 'とっきゅう', 'tokkyuu', 'Ekspres', '特急券 (Tiket ekspres)', 2),
('時計', 'とけい', 'tokei', 'Jam', '時計を見る (Lihat jam)', 2),
('どこか', 'どこか', 'dokoka', 'Suatu tempat', 'どこかへ行く (Pergi ke suatu tempat)', 2),
('床屋', 'とこや', 'tokoya', 'Tukang Cukur', '床屋へ行く (Pergi cukur)', 2),
('途中', 'とちゅう', 'tochuu', 'Di tengah jalan', '帰る途中 (Di jalan pulang)', 2),
('特急', 'とっきゅう', 'tokkyuu', 'Ekspres', '特急電車 (Kereta ekspres)', 2),
('届く', 'とどく', 'todoku', 'Sampai', '手紙が届く (Surat sampai)', 2),
('泊まる', 'とまる', 'tomaru', 'Menginap', 'ホテルに泊まる (Nginap di hotel)', 2),
('止める', 'とめる', 'tomeru', 'Menghentikan', '車を止める (Setop mobil)', 2),
('取り替える', 'とりかえる', 'torikaeru', 'Menukar', 'タイヤを取り替える (Ganti ban)', 2),
('泥', 'どろ', 'doro', 'Lumpur', '泥だらけ (Penuh lumpur)', 2),
('どんどん', 'どんどん', 'dondon', 'Terus menerus', 'どんどん食べる (Makan terus)', 2);
